AWSTemplateFormatVersion: "2010-09-09"
Description: Internal Application Load Balancer for Application Tier

Parameters:
  Environment:
    Type: String
    AllowedValues: [dev, prod]

  ProjectName:
    Type: String

  VpcId:
    Type: AWS::EC2::VPC::Id

  # 🔧 CORREÇÃO: String + Split (compatível com Master)
  PrivateAppSubnets:
    Type: String

  WebSecurityGroupId:
    Type: String

Resources:
  ALBAppSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow traffic from Web Tier on port 8080
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 8080
          ToPort: 8080
          SourceSecurityGroupId: !Ref WebSecurityGroupId
      Tags:
        - Key: Name
          Value: !Sub "${ProjectName}-${Environment}-alb-app-sg"

  ALBApp:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: !Sub "${ProjectName}-${Environment}-alb-app"
      Scheme: internal
      Type: application
      Subnets: !Split [",", !Ref PrivateAppSubnets]
      SecurityGroups:
        - !Ref ALBAppSecurityGroup

  AppTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: !Sub "${ProjectName}-${Environment}-tg-app"
      VpcId: !Ref VpcId
      Port: 8080
      Protocol: HTTP
      TargetType: instance
      HealthCheckPath: /health
      Matcher:
        HttpCode: "200"

  ALBAppListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !Ref ALBApp
      Port: 8080
      Protocol: HTTP
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref AppTargetGroup

Outputs:
  ALBAppDNS:
    Value: !GetAtt ALBApp.DNSName

  AppTargetGroupArn:
    Value: !Ref AppTargetGroup

  ALBAppSecurityGroupId:
    Value: !Ref ALBAppSecurityGroup
