AWSTemplateFormatVersion: "2010-09-09"
Description: Application Load Balancer para o Backend Java

Parameters:
  Environment: { Type: String }
  ProjectName: { Type: String }
  VpcId: { Type: String }
  PublicSubnets: { Type: String }
  # Adicionei este parâmetro para receber o SG da Master Stack
  AlbSecurityGroupId: { Type: String } 
  PrivateAppSubnets: { Type: String }
  PrivateDbSubnets: { Type: String }
  CertificateARN: { Type: String }
  LatestAMIId: { Type: String }
  KeyName: { Type: String }
  DBUsername: { Type: String }
  DBPassword: { Type: String }

Resources:
  # 1. O Load Balancer
  ApplicationLoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: !Sub "${ProjectName}-${Environment}-alb"
      Subnets: !Split [",", !Ref PublicSubnets]
      SecurityGroups: 
        - !Ref AlbSecurityGroupId # Agora usa o parâmetro direto
      Tags: [{ Key: Name, Value: !Sub "${ProjectName}-${Environment}-alb" }]

  # 2. Target Group (Porta 8080 para o Postman/Java)
  WebTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: !Sub "${ProjectName}-${Environment}-tg"
      VpcId: !Ref VpcId
      Protocol: HTTP
      Port: 8080
      HealthCheckPath: /actuator/health

      TargetType: instance
      HealthCheckIntervalSeconds: 30
      HealthyThresholdCount: 2

  # 3. Listener HTTP (Porta 80)
  HttpListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !Ref ApplicationLoadBalancer
      Port: 80
      Protocol: HTTP
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref WebTargetGroup

Outputs:
  ALBWebDNS:
    Value: !GetAtt ApplicationLoadBalancer.DNSName
  WebTargetGroupArn:
    Value: !Ref WebTargetGroup