AWSTemplateFormatVersion: "2010-09-09"
Description: Application Load Balancer para o Backend Java

Parameters:
  Environment:
    Type: String

  ProjectName:
    Type: String

  VpcId:
    Type: AWS::EC2::VPC::Id

  PublicSubnets:
    Type: String
    Description: Subnets públicas separadas por vírgula

  AlbSecurityGroupId:
    Type: AWS::EC2::SecurityGroup::Id

Resources:

  # Application Load Balancer
  ApplicationLoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: !Sub "${ProjectName}-${Environment}-alb"
      Scheme: internet-facing
      Type: application
      Subnets: !Split [ ",", !Ref PublicSubnets ]
      SecurityGroups:
        - !Ref AlbSecurityGroupId
      Tags:
        - Key: Name
          Value: !Sub "${ProjectName}-${Environment}-alb"

  # Target Group (Backend Java)
  WebTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: !Sub "${ProjectName}-${Environment}-tg"
      VpcId: !Ref VpcId
      Protocol: HTTP
      Port: 8080
      TargetType: instance

      HealthCheckPath: /actuator/health
      HealthCheckProtocol: HTTP
      HealthCheckIntervalSeconds: 30
      HealthCheckTimeoutSeconds: 5
      HealthyThresholdCount: 2
      UnhealthyThresholdCount: 2

      Matcher:
        HttpCode: 200

  # Listener HTTP (porta 80)
  HttpListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !Ref ApplicationLoadBalancer
      Port: 80
      Protocol: HTTP
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref WebTargetGroup

Outputs:
  ALBWebDNS:
    Description: DNS público do ALB
    Value: !GetAtt ApplicationLoadBalancer.DNSName

  WebTargetGroupArn:
    Description: ARN do Target Group
    Value: !Ref WebTargetGroup
