AWSTemplateFormatVersion: "2010-09-09"
Description: Módulo Load Balancer Web (ALB) - HTTPS com Certificado via Master Stack

Parameters:
  Environment:
    Type: String

  ProjectName:
    Type: String

  VpcId:
    Type: AWS::EC2::VPC::Id

  PublicSubnets:
    Type: String

  ALBWebSecurityGroupId:
    Type: AWS::EC2::SecurityGroup::Id

  # Recebe o ARN diretamente da Master Stack
  CertificateARN:
    Type: String

Resources:

  ALBWeb:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: !Sub "${ProjectName}-${Environment}-alb-web"
      Scheme: internet-facing
      Type: application
      Subnets: !Split [",", !Ref PublicSubnets]
      SecurityGroups:
        - !Ref ALBWebSecurityGroupId

  WebTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: !Sub "${ProjectName}-${Environment}-tg-web"
      VpcId: !Ref VpcId
      Port: 80
      Protocol: HTTP
      TargetType: instance
      HealthCheckPath: /
      HealthCheckIntervalSeconds: 30
      HealthyThresholdCount: 2
      UnhealthyThresholdCount: 3
      Matcher:
        HttpCode: 200-399

  ListenerHTTPS:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !Ref ALBWeb
      Port: 443
      Protocol: HTTPS
      Certificates:
        - CertificateArn: !Ref CertificateARN
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref WebTargetGroup

  ListenerHTTP:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !Ref ALBWeb
      Port: 80
      Protocol: HTTP
      DefaultActions:
        - Type: redirect
          RedirectConfig:
            Protocol: HTTPS
            Port: "443"
            StatusCode: HTTP_301

Outputs:
  ALBWebDNS:
    Description: DNS público do ALB Web
    Value: !GetAtt ALBWeb.DNSName

  ALBHostedZoneId:
    Description: Hosted Zone ID do ALB
    Value: !GetAtt ALBWeb.CanonicalHostedZoneID

  WebTargetGroupArn:
    Description: ARN do Target Group Web
    Value: !Ref WebTargetGroup
