AWSTemplateFormatVersion: "2010-09-09"
Description: Internal Application Load Balancer for Application Tier

Parameters:
  Environment:
    Type: String
    AllowedValues: [dev, prod]
  ProjectName:
    Type: String
  VpcId:
    Type: AWS::EC2::VPC::Id
  PrivateAppSubnets:
    Type: List<AWS::EC2::Subnet::Id>
  WebSecurityGroupId:
    Type: String # Alterado para String para evitar conflitos de importação

Resources:
  ALBAppSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: "Allow traffic from Web Tier on port 8080"
      VpcId: { Ref: VpcId }
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 8080
          ToPort: 8080
          SourceSecurityGroupId: { Ref: WebSecurityGroupId }
      Tags:
        - Key: Name
          Value: { Fn::Sub: "${ProjectName}-${Environment}-alb-app-sg" }

  ALBApp:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: { Fn::Sub: "${ProjectName}-${Environment}-alb-app" }
      Scheme: internal
      Type: application
      Subnets: { Ref: PrivateAppSubnets }
      SecurityGroups: 
        - { Ref: ALBAppSecurityGroup }

  AppTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: { Fn::Sub: "${ProjectName}-${Environment}-tg-app" }
      Port: 8080
      Protocol: HTTP
      VpcId: { Ref: VpcId }
      TargetType: instance
      HealthCheckPath: /health
      Matcher: { HttpCode: "200" }

  ALBAppListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: { Ref: ALBApp }
      Port: 8080 # Ajustado para 8080 para alinhar com a aplicação
      Protocol: HTTP
      DefaultActions:
        - Type: forward
          TargetGroupArn: { Ref: AppTargetGroup }

Outputs:
  ALBAppDNS:
    Value: { Fn::GetAtt: [ALBApp, DNSName] }
  AppTargetGroupArn:
    Value: { Ref: AppTargetGroup }
  ALBAppSecurityGroupId:
    Value: { Ref: ALBAppSecurityGroup }