AWSTemplateFormatVersion: "2010-09-09"
Description: Módulo Load Balancer Web (ALB) - Configuração de Tráfego HTTPS

Parameters:
  Environment: { Type: String }
  ProjectName: { Type: String }
  VpcId: { Type: AWS::EC2::VPC::Id }
  PublicSubnets: { Type: List<AWS::EC2::Subnet::Id> }
  ALBWebSecurityGroupId: { Type: String }

Resources:
  ALBWeb:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: !Sub "${ProjectName}-${Environment}-alb-web"
      Subnets: !Ref PublicSubnets
      SecurityGroups: 
        - !Ref ALBWebSecurityGroupId
      Scheme: internet-facing

  WebTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      VpcId: !Ref VpcId
      Port: 80
      Protocol: HTTP
      TargetType: instance
      HealthCheckPath: /

  ListenerHTTPS:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !Ref ALBWeb
      Port: 443
      Protocol: HTTPS
      Certificates:
        - CertificateArn: !ImportValue 
            Fn::Sub: "${ProjectName}-${Environment}-CertificateArn"
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref WebTargetGroup

  ListenerHTTP:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !Ref ALBWeb
      Port: 80
      Protocol: HTTP
      DefaultActions:
        - Type: redirect
          RedirectConfig:
            Protocol: HTTPS
            Port: "443"
            StatusCode: HTTP_301

Outputs:
  ALBWebDNS:
    Value: !GetAtt ALBWeb.DNSName
  ALBHostedZoneId:
    Value: !GetAtt ALBWeb.CanonicalHostedZoneID
  # SIM: Esta é a peça que faltava para o Master funcionar
  WebTargetGroupArn:
    Value: !Ref WebTargetGroup