AWSTemplateFormatVersion: "2010-09-09"
Description: Application Load Balancer (ALB) para API - HTTPS

Parameters:
  ProjectName:
    Type: String
  Environment:
    Type: String
  CertificateARN:
    Type: String

Resources:
  # ==================================================
  # Load Balancer - Porta de entrada pública
  # ==================================================
  ApplicationLoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: !Sub "${ProjectName}-${Environment}-alb"
      Scheme: internet-facing
      Type: application
      Subnets:
        - Fn::ImportValue: !Sub "${ProjectName}-vpc-${Environment}-public-az1"
        - Fn::ImportValue: !Sub "${ProjectName}-vpc-${Environment}-public-az2"
      SecurityGroups:
        - Fn::ImportValue: !Sub "${ProjectName}-${Environment}-AlbSG"

  # ==================================================
  # Target Group - Onde o backend será registrado
  # ==================================================
  AppTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: !Sub "${ProjectName}-${Environment}-tg"
      VpcId:
        Fn::ImportValue: !Sub "${ProjectName}-vpc-${Environment}-id"
      Port: 8080 # Porta padrão Spring Boot
      Protocol: HTTP
      TargetType: instance
      HealthCheckPath: /actuator/health
      HealthCheckIntervalSeconds: 30
      HealthCheckTimeoutSeconds: 5
      HealthyThresholdCount: 2
      UnhealthyThresholdCount: 3
      Matcher:
        HttpCode: "200,302" # Aceita 302 caso haja redirecionamento de auth

  # ==================================================
  # Listeners (HTTPS e Redirecionamento HTTP)
  # ==================================================
  HttpsListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !Ref ApplicationLoadBalancer
      Port: 443
      Protocol: HTTPS
      Certificates:
        - CertificateArn: !Ref CertificateARN
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref AppTargetGroup

  HttpListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !Ref ApplicationLoadBalancer
      Port: 80
      Protocol: HTTP
      DefaultActions:
        - Type: redirect
          RedirectConfig:
            Protocol: HTTPS
            Port: "443"
            StatusCode: HTTP_301

Outputs:
  AlbDnsName:
    Value: !GetAtt ApplicationLoadBalancer.DNSName
    Export:
      Name: !Sub "${ProjectName}-${Environment}-AlbDnsName"

  TargetGroupArn:
    Value: !Ref AppTargetGroup
    Export:
      Name: !Sub "${ProjectName}-${Environment}-TargetGroupArn"

  AlbCanonicalHostedZoneID:
    Value: !GetAtt ApplicationLoadBalancer.CanonicalHostedZoneID
    Export:
      Name: !Sub "${ProjectName}-${Environment}-AlbHostedZoneId"

  AlbFullName:
    Value: !GetAtt ApplicationLoadBalancer.LoadBalancerFullName
    Export:
      Name: !Sub "${ProjectName}-${Environment}-AlbFullName"    



 


