AWSTemplateFormatVersion: "2010-09-09"
Description: Auto Scaling Group for Application Tier (Java 21)

Parameters:
  Environment:
    Type: String
    AllowedValues: [dev, prod]

  ProjectName:
    Type: String

  VpcId:
    Type: AWS::EC2::VPC::Id

  PrivateAppSubnets:
    Type: List<AWS::EC2::Subnet::Id>

  AppTargetGroupArn:
    Type: String
    Description: Target Group ARN from ALB App

  ALBAppSecurityGroupId:
    Type: AWS::EC2::SecurityGroup::Id
    Description: Security Group do ALB interno

  InstanceType:
    Type: String
    Default: t3.small

  LatestAMIId:
    Type: AWS::EC2::Image::Id

  KeyName:
    Type: AWS::EC2::KeyPair::KeyName

Resources:

  ############################
  # IAM INSTANCE PROFILE
  ############################
  AppInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles:
        - stock-manager-prod-ec2-role

  ############################
  # SECURITY GROUP
  ############################
  AppInstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow traffic from ALB App on port 8080
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 8080
          ToPort: 8080
          SourceSecurityGroupId: !Ref ALBAppSecurityGroupId
      Tags:
        - Key: Name
          Value: !Sub "${ProjectName}-${Environment}-app-sg"

  ############################
  # LAUNCH TEMPLATE
  ############################
  AppLaunchTemplate:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateName: !Sub "${ProjectName}-${Environment}-app-lt"
      LaunchTemplateData:
        IamInstanceProfile:
          Name: !Ref AppInstanceProfile
        ImageId: !Ref LatestAMIId
        InstanceType: !Ref InstanceType
        KeyName: !Ref KeyName
        SecurityGroupIds:
          - !Ref AppInstanceSecurityGroup
        UserData:
          Fn::Base64: !Sub |
            #!/bin/bash
            yum update -y
            yum install -y java-21-amazon-corretto

            echo "Application Tier Java 21 - ${Environment}" > /opt/app.txt

            # Exemplo de start da aplicação
            # aws s3 cp s3://seu-bucket/stock-manager.jar /opt/stock-manager.jar
            # nohup java -jar /opt/stock-manager.jar > /var/log/app.log 2>&1 &

  ############################
  # AUTO SCALING GROUP
  ############################
  AppAutoScalingGroup:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      VPCZoneIdentifier: !Ref PrivateAppSubnets
      LaunchTemplate:
        LaunchTemplateId: !Ref AppLaunchTemplate
        Version: !GetAtt AppLaunchTemplate.LatestVersionNumber
      MinSize: "2"
      MaxSize: "4"
      DesiredCapacity: "2"
      TargetGroupARNs:
        - !Ref AppTargetGroupArn
      HealthCheckType: ELB
      HealthCheckGracePeriod: 300
      Tags:
        - Key: Name
          Value: !Sub "${ProjectName}-${Environment}-app"
          PropagateAtLaunch: true

Outputs:
  AppASGName:
    Value: !Ref AppAutoScalingGroup

  AppSecurityGroupId:
    Value: !Ref AppInstanceSecurityGroup
