AWSTemplateFormatVersion: "2010-09-09"
Description: Backend Layer - Auto Scaling Group para Java App

Parameters:
  Environment: { Type: String }
  ProjectName: { Type: String }
  VpcId: { Type: String }
  PrivateAppSubnets: { Type: List<AWS::EC2::Subnet::Id> }
  AppTargetGroupArn: { Type: String }
  InstanceType: { Type: String } # Adicionado para corrigir E3043
  LatestAMIId: { Type: AWS::EC2::Image::Id }
  KeyName: { Type: AWS::EC2::KeyPair::KeyName }

Resources:
  AppLaunchTemplate:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateName: !Sub "${ProjectName}-${Environment}-app-launch-template"
      LaunchTemplateData:
        ImageId: !Ref LatestAMIId
        InstanceType: !Ref InstanceType
        KeyName: !Ref KeyName
        # Security Groups devem ser passados aqui via IDs
        TagSpecifications:
          - ResourceType: instance
            Tags:
              - Key: Name
                Value: !Sub "${ProjectName}-${Environment}-app-instance"

  AppAsg:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      AutoScalingGroupName: !Sub "${ProjectName}-${Environment}-app-asg"
      VPCZoneIdentifier: !Ref PrivateAppSubnets
      LaunchTemplate:
        LaunchTemplateId: !Ref AppLaunchTemplate
        Version: !GetAtt AppLaunchTemplate.LatestVersionNumber
      MinSize: "1"
      MaxSize: "3"
      DesiredCapacity: "1"
      TargetGroupARNs:
        - !Ref AppTargetGroupArn
      Tags:
        - Key: Name
          Value: !Sub "${ProjectName}-${Environment}-app-asg"
          PropagateAtLaunch: true

Outputs:
  AppAsgName:
    Value: !Ref AppAsg