AWSTemplateFormatVersion: "2010-09-09"
Description: App Backend - ASG com bootstrap correto da aplicação

Parameters:
  Environment:
    Type: String

  ProjectName:
    Type: String

  PrivateAppSubnets:
    Type: List<AWS::EC2::Subnet::Id>

  AppTargetGroupArn:
    Type: String

  InstanceType:
    Type: String

  LatestAMIId:
    Type: AWS::EC2::Image::Id

  KeyName:
    Type: AWS::EC2::KeyPair::KeyName

Resources:

  AppLaunchTemplate:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateName: !Sub "${ProjectName}-${Environment}-app-lt"
      LaunchTemplateData:

        IamInstanceProfile:
          Name: stock-manager-ec2-role

        ImageId: !Ref LatestAMIId
        InstanceType: !Ref InstanceType
        KeyName: !Ref KeyName

        SecurityGroupIds:
          - Fn::ImportValue:
              Fn::Sub: "${ProjectName}-${Environment}-AppSG"

        UserData:
          Fn::Base64: |
            #!/bin/bash
            set -xe

            yum update -y
            yum install -y java-21-amazon-corretto awscli

            mkdir -p /opt/app
            cd /opt/app

            aws s3 cp s3://stock-manager-prod-artifacts/app/app.jar app.jar
            chmod +x app.jar

            nohup java -jar app.jar \
              --server.port=8080 \
              > /var/log/app.log 2>&1 &

            echo "Aplicação iniciada com sucesso" > /home/ec2-user/status.txt

        TagSpecifications:
          - ResourceType: instance
            Tags:
              - Key: Name
                Value: !Sub "${ProjectName}-${Environment}-app-instance"

  AppASG:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      AutoScalingGroupName: !Sub "${ProjectName}-${Environment}-app-asg"
      VPCZoneIdentifier: !Ref PrivateAppSubnets

      LaunchTemplate:
        LaunchTemplateId: !Ref AppLaunchTemplate
        Version: !GetAtt AppLaunchTemplate.LatestVersionNumber

      MinSize: "1"
      MaxSize: "1"
      DesiredCapacity: "1"

      HealthCheckType: ELB
      HealthCheckGracePeriod: 300

      TargetGroupARNs:
        - !Ref AppTargetGroupArn

      Tags:
        - Key: Name
          Value: !Sub "${ProjectName}-${Environment}-app-server"
          PropagateAtLaunch: true

Outputs:
  AsgName:
    Description: Auto Scaling Group Name
    Value: !Ref AppASG
