AWSTemplateFormatVersion: "2010-09-09"
Description: App Backend - ASG (estável para configuração inicial)

Parameters:
  Environment:
    Type: String

  ProjectName:
    Type: String

  PrivateAppSubnets:
    Type: List<AWS::EC2::Subnet::Id>

  AppTargetGroupArn:
    Type: String

  InstanceType:
    Type: String

  LatestAMIId:
    Type: AWS::EC2::Image::Id

  KeyName:
    Type: AWS::EC2::KeyPair::KeyName

Resources:

  AppLaunchTemplate:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateName: !Sub "${ProjectName}-${Environment}-app-lt"
      LaunchTemplateData:
        ImageId: !Ref LatestAMIId
        InstanceType: !Ref InstanceType
        KeyName: !Ref KeyName
        SecurityGroupIds:
          - Fn::ImportValue:
              Fn::Sub: "${ProjectName}-${Environment}-AppSG"
        UserData:
          Fn::Base64: |
            #!/bin/bash
            yum update -y
            yum install -y java-21-amazon-corretto
            echo "EC2 pronta" > /home/ec2-user/status.txt
        TagSpecifications:
          - ResourceType: instance
            Tags:
              - Key: Name
                Value: !Sub "${ProjectName}-${Environment}-app-instance"

  AppASG:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      AutoScalingGroupName: !Sub "${ProjectName}-${Environment}-app-asg"
      VPCZoneIdentifier: !Ref PrivateAppSubnets
      LaunchTemplate:
        LaunchTemplateId: !Ref AppLaunchTemplate
        Version: !GetAtt AppLaunchTemplate.LatestVersionNumber
      MinSize: "1"
      MaxSize: "1"
      DesiredCapacity: "1"
      HealthCheckType: EC2
      HealthCheckGracePeriod: 300
      TargetGroupARNs:
        - !Ref AppTargetGroupArn
      Tags:
        - Key: Name
          Value: !Sub "${ProjectName}-${Environment}-app-server"
          PropagateAtLaunch: true

Outputs:
  AsgName:
    Description: Auto Scaling Group Name
    Value: !Ref AppASG
