AWSTemplateFormatVersion: "2010-09-09"
Description: ASG da aplicação + EC2 + UserData conectado ao IAM dinâmico

Parameters:
  ProjectName:
    Type: String
  Environment:
    Type: String
  AmiId:
    Type: AWS::EC2::Image::Id
  InstanceType:
    Type: String
    Default: t3.small
  KeyPairName:
    Type: AWS::EC2::KeyPair::KeyName

  DBUsername:
    Type: String
  DBPassword:
    Type: String
    NoEcho: true
  DBName:
    Type: String
    Default: stockmanagerprod

Resources:
  AppLaunchTemplate:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateName: !Sub "${ProjectName}-${Environment}-lt"
      LaunchTemplateData:
        ImageId: !Ref AmiId
        InstanceType: !Ref InstanceType
        KeyName: !Ref KeyPairName

        IamInstanceProfile:
          Name: !ImportValue 
            Fn::Sub: "${ProjectName}-${Environment}-AppInstanceProfile"

        SecurityGroupIds:
          - Fn::ImportValue: !Sub "${ProjectName}-${Environment}-AppSG"

        UserData:
          Fn::Base64:
            Fn::Sub:
              - |
                #!/bin/bash
                # Redireciona logs para depuração caso o UserData falhe
                exec > >(tee /var/log/user-data.log|logger -t user-data -s 2>/dev/console) 2>&1
                set -e

                echo "== Atualizando sistema e dependências =="
                dnf update -y
                dnf install -y amazon-ssm-agent java-21-amazon-corretto awscli ruby wget

                echo "== Garantindo Agente SSM (Managed Status) =="
                systemctl enable amazon-ssm-agent
                systemctl start amazon-ssm-agent

                echo "== Instalando CodeDeploy Agent com Resiliência =="
                cd /home/ec2-user
                # Loop de retry para evitar falha se o NAT Gateway oscilar no início
                for i in {1..5}; do 
                  wget https://aws-codedeploy-us-east-1.s3.us-east-1.amazonaws.com/latest/install && break || sleep 10
                done
                chmod +x ./install
                ./install auto
                systemctl enable codedeploy-agent
                systemctl start codedeploy-agent

                echo "== Diretório da aplicação =="
                mkdir -p /home/ec2-user/app
                chown -R ec2-user:ec2-user /home/ec2-user/app

                echo "== Criando variáveis de ambiente globais =="
                cat <<EOF > /etc/profile.d/app_env.sh
                export DB_HOST=${DBEndpoint}
                export DB_PORT=5432
                export DB_NAME=${DBName}
                export DB_USERNAME=${DBUsername}
                export DB_PASSWORD=${DBPassword}
                EOF

                # Permissão 644 para que o ec2-user consiga ler as variáveis
                chmod 644 /etc/profile.d/app_env.sh
                chown root:root /etc/profile.d/app_env.sh

                echo "UserData finalizado com sucesso"

              - DBEndpoint:
                  Fn::ImportValue: !Sub "${ProjectName}-${Environment}-DBEndpoint"
                DBName: !Ref DBName
                DBUsername: !Ref DBUsername
                DBPassword: !Ref DBPassword

  AppAsg:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      AutoScalingGroupName: !Sub "${ProjectName}-${Environment}-asg"

      LaunchTemplate:
        LaunchTemplateId: !Ref AppLaunchTemplate
        Version: !GetAtt AppLaunchTemplate.LatestVersionNumber

      MinSize: "1"
      MaxSize: "2"
      DesiredCapacity: "1"

      VPCZoneIdentifier:
        - Fn::ImportValue: !Sub "${ProjectName}-vpc-${Environment}-private-app-az1"
        - Fn::ImportValue: !Sub "${ProjectName}-vpc-${Environment}-private-app-az2"

      TargetGroupARNs:
        - Fn::ImportValue: !Sub "${ProjectName}-${Environment}-TargetGroupArn"

      HealthCheckType: ELB
      HealthCheckGracePeriod: 300

      Tags:
        - Key: Name
          Value: !Sub "${ProjectName}-${Environment}-app"
          PropagateAtLaunch: true

Outputs:
  AutoScalingGroupName:
    Description: Nome do ASG para integração com CodeDeploy
    Value: !Ref AppAsg
    Export:
      Name: !Sub "${ProjectName}-${Environment}-AsgName"

      

