AWSTemplateFormatVersion: "2010-09-09"
Description: Módulo de Computação - Produção (ASG + IAM) Corrigido para CodeDeploy e Importação de VPC

Parameters:
  ProjectName:
    Type: String
  Environment:
    Type: String
  AmiId:
    Type: AWS::EC2::Image::Id
  InstanceType:
    Type: String
    Default: t3.small
  KeyPairName:
    Type: AWS::EC2::KeyPair::KeyName
  DBUsername:
    Type: String
  DBPassword:
    Type: String
    NoEcho: true

Resources:

  # ==================================================
  # IAM Role da EC2 (Pilar 1: Permissões)
  # ==================================================
  AppInstanceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        # Essencial para o status "Managed: true"
        - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
        - arn:aws:iam::aws:policy/AmazonS3ReadOnlyAccess
        - arn:aws:iam::aws:policy/CloudWatchAgentServerPolicy

  AppInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles:
        - !Ref AppInstanceRole

  # ==================================================
  # Launch Template (Pilar 2: Configuração de Inicialização)
  # ==================================================
  AppLaunchTemplate:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateName: !Sub "${ProjectName}-${Environment}-lt"
      LaunchTemplateData:
        IamInstanceProfile:
          Name: !Ref AppInstanceProfile
        ImageId: !Ref AmiId
        InstanceType: !Ref InstanceType
        KeyName: !Ref KeyPairName
        SecurityGroupIds:
          # IMPORTA o SG criado no Job 1 (VPC/Foundation)
          - Fn::ImportValue: !Sub "${ProjectName}-${Environment}-AppSG"

        UserData:
          Fn::Base64:
            Fn::Sub:
              - |
                #!/bin/bash
                # 1. Atualização e Instalação de dependências
                yum update -y
                yum install -y java-21-amazon-corretto awscli ruby wget

                # 2. Instalação do AWS CodeDeploy Agent
                cd /home/ec2-user
                wget https://aws-codedeploy-us-east-1.s3.us-east-1.amazonaws.com/latest/install
                chmod +x ./install
                ./install auto
                systemctl enable codedeploy-agent
                systemctl start codedeploy-agent

                # 3. Preparação do diretório e variáveis para o Backend
                mkdir -p /home/ec2-user/app
                echo "export DB_URL=${RDSUrl}" >> /etc/profile.d/app_env.sh
                echo "export DB_USERNAME=${DBUsername}" >> /etc/profile.d/app_env.sh
                echo "export DB_PASSWORD=${DBPassword}" >> /etc/profile.d/app_env.sh
                chmod +x /etc/profile.d/app_env.sh

              - RDSUrl:
                  # IMPORTA o Endpoint do RDS criado no Job 2 (Master)
                  Fn::ImportValue: !Sub "${ProjectName}-${Environment}-DBEndpoint"
                DBUsername: !Ref DBUsername
                DBPassword: !Ref DBPassword

  # ==================================================
  # Auto Scaling Group (Pilar 3: Rede e Disponibilidade)
  # ==================================================
  AppAsg:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      AutoScalingGroupName: !Sub "${ProjectName}-${Environment}-asg"
      LaunchTemplate:
        LaunchTemplateId: !Ref AppLaunchTemplate
        Version: !GetAtt AppLaunchTemplate.LatestVersionNumber
      MinSize: "1"
      MaxSize: "2"
      DesiredCapacity: "1"
      VPCZoneIdentifier:
        # IMPORTA as subnets privadas criadas no Job 1 (VPC)
        - Fn::ImportValue: !Sub "${ProjectName}-vpc-${Environment}-private-app-az1"
        - Fn::ImportValue: !Sub "${ProjectName}-vpc-${Environment}-private-app-az2"
      TargetGroupARNs:
        # IMPORTA o Target Group criado no Job 2 (Master/ALB)
        - Fn::ImportValue: !Sub "${ProjectName}-${Environment}-TargetGroupArn"
      HealthCheckType: ELB
      HealthCheckGracePeriod: 300
      Tags:
        - Key: Name
          Value: !Sub "${ProjectName}-${Environment}-app"
          PropagateAtLaunch: true

Outputs:
  AutoScalingGroupName:
    Description: Nome para integração com CodeDeploy
    Value: !Ref AppAsg
    Export:
      Name: !Sub "${ProjectName}-${Environment}-AsgName"