AWSTemplateFormatVersion: "2010-09-09"
Description: CloudFront Distribution (EDGE)

Parameters:
  ProjectName:
    Type: String
  Environment:
    Type: String
  CertificateARN:
    Type: String
  DomainName:
    Type: String

Resources:
  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Enabled: true
        Comment: !Sub "${ProjectName}-${Environment}-cloudfront"

        Aliases:
          - !Ref DomainName

        Origins:
          - Id: alb-origin
            DomainName:
              Fn::ImportValue: !Sub "${ProjectName}-${Environment}-AlbDnsName"
            CustomOriginConfig:
              HTTPPort: 80
              HTTPSPort: 443
              OriginProtocolPolicy: https-only

        DefaultCacheBehavior:
          TargetOriginId: alb-origin
          ViewerProtocolPolicy: redirect-to-https
          AllowedMethods:
            - GET
            - HEAD
            - OPTIONS
            - PUT
            - POST
            - PATCH
            - DELETE
          CachedMethods:
            - GET
            - HEAD
          Compress: true
          ForwardedValues:
            QueryString: true
            Cookies:
              Forward: all

        ViewerCertificate:
          AcmCertificateArn: !Ref CertificateARN
          SslSupportMethod: sni-only
          MinimumProtocolVersion: TLSv1.2_2021

Outputs:
  # Alterado para 'CloudFrontDNS' para bater com o que o master.yaml espera
  CloudFrontDNS:
    Description: "CloudFront distribution domain name"
    Value: !GetAtt CloudFrontDistribution.DomainName

  CloudFrontHostedZoneId:
    Description: "Hosted Zone ID for CloudFront (Route53 Alias)"
    Value: Z2FDTNDATAQYW2

