AWSTemplateFormatVersion: "2010-09-09"
Description: CloudWatch Alarm para Auto Scaling Group

Parameters:
  ProjectName:
    Type: String
  Environment:
    Type: String

Resources:

  AsgHighCPUAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub "${ProjectName}-${Environment}-asg-high-cpu"
      Namespace: AWS/EC2
      MetricName: CPUUtilization
      Statistic: Average
      Period: 60
      EvaluationPeriods: 2
      Threshold: 75
      ComparisonOperator: GreaterThanOrEqualToThreshold
      TreatMissingData: notBreaching
      Dimensions:
        - Name: AutoScalingGroupName
          Value:
            Fn::ImportValue: !Sub "${ProjectName}-${Environment}-AsgName"

Outputs:
  AsgHighCPUAlarmName:
    Description: Nome do alarme de CPU alta do ASG
    Value: !Ref AsgHighCPUAlarm
