AWSTemplateFormatVersion: "2010-09-09"
Description: "CloudFront Distribution (EDGE) apontando para ALB com WAF e HTTPS"

Parameters:
  ProjectName:
    Type: String

  Environment:
    Type: String

  CertificateARN:
    Type: String
    Description: "ACM Certificate ARN (obrigatoriamente em us-east-1)"

  DomainName:
    Type: String
    Description: "Domínio que será usado no CloudFront (ex: api.asantanadev.com)"

  WebACLArn:
    Type: String
    Description: "ARN do WAFv2 (Scope = CLOUDFRONT)"

Resources:
  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Enabled: true
        Comment: !Sub "${ProjectName}-${Environment}-cloudfront"

        WebACLId: !Ref WebACLArn

        PriceClass: PriceClass_100
        HttpVersion: http2

        Aliases:
          - !Ref DomainName

        Origins:
          - Id: alb-origin
            DomainName:
              Fn::ImportValue: !Sub "${ProjectName}-${Environment}-AlbDnsName"
            CustomOriginConfig:
              HTTPPort: 80
              HTTPSPort: 443
              OriginProtocolPolicy: https-only
              OriginSSLProtocols:
                - TLSv1.2

        DefaultCacheBehavior:
          TargetOriginId: alb-origin
          ViewerProtocolPolicy: redirect-to-https

          AllowedMethods:
            - GET
            - HEAD
            - OPTIONS
            - PUT
            - POST
            - PATCH
            - DELETE

          CachedMethods:
            - GET
            - HEAD

          Compress: true

          ForwardedValues:
            QueryString: true
            Cookies:
              Forward: all

        ViewerCertificate:
          AcmCertificateArn: !Ref CertificateARN
          SslSupportMethod: sni-only
          MinimumProtocolVersion: TLSv1.2_2021

Outputs:
  CloudFrontDNS:
    Description: "DNS público do CloudFront"
    Value: !GetAtt CloudFrontDistribution.DomainName
    Export:
      Name: !Sub "${ProjectName}-${Environment}-CloudFrontDNS"

  CloudFrontHostedZoneId:
    Description: "Hosted Zone ID fixo do CloudFront para Alias no Route53"
    Value: "Z2FDTNDATAQYW2"
    Export:
      Name: !Sub "${ProjectName}-${Environment}-CloudFrontHostedZoneId"

  CloudFrontDistributionId:
    Description: "ID da distribuição CloudFront (útil para automações futuras)"
    Value: !Ref CloudFrontDistribution
    Export:
      Name: !Sub "${ProjectName}-${Environment}-CloudFrontDistributionId"
