AWSTemplateFormatVersion: "2010-09-09"
Description: Edge Layer - Route53, CloudFront, S3, WAF and ACM

Parameters:
  Environment:
    Type: String
    AllowedValues:
      - dev
      - prod

  ProjectName:
    Type: String

  DomainName:
    Type: String

  HostedZoneId:
    Type: String

  CertificateARN:
    Type: String

  ALBDomainName:
    Type: String

Resources:

  StaticContentBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName:
        Fn::Sub: "${ProjectName}-${Environment}-static-content"
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      VersioningConfiguration:
        Status: Enabled

  CloudFrontOAC:
    Type: AWS::CloudFront::OriginAccessControl
    Properties:
      OriginAccessControlConfig:
        Name:
          Fn::Sub: "${ProjectName}-${Environment}-oac"
        OriginAccessControlOriginType: s3
        SigningBehavior: always
        SigningProtocol: sigv4

  StaticBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket:
        Ref: StaticContentBucket
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: cloudfront.amazonaws.com
            Action: s3:GetObject
            Resource:
              Fn::Sub: "${StaticContentBucket.Arn}/*"
            Condition:
              StringEquals:
                AWS:SourceArn:
                  Fn::Sub: "arn:aws:cloudfront::${AWS::AccountId}:distribution/*"

  WebACL:
    Type: AWS::WAFv2::WebACL
    Properties:
      Name:
        Fn::Sub: "${ProjectName}-${Environment}-waf"
      Scope: CLOUDFRONT
      DefaultAction:
        Allow: {}
      VisibilityConfig:
        SampledRequestsEnabled: true
        CloudWatchMetricsEnabled: true
        MetricName: waf
      Rules:
        - Name: AWSManagedRulesCommonRuleSet
          Priority: 1
          OverrideAction:
            None: {}
          Statement:
            ManagedRuleGroupStatement:
              VendorName: AWS
              Name: AWSManagedRulesCommonRuleSet
          VisibilityConfig:
            SampledRequestsEnabled: true
            CloudWatchMetricsEnabled: true
            MetricName: common

  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Enabled: true

        Aliases:
          - Ref: DomainName

        Origins:
          - Id: S3Origin
            DomainName:
              Fn::GetAtt:
                - StaticContentBucket
                - RegionalDomainName
            OriginAccessControlId:
              Ref: CloudFrontOAC
            S3OriginConfig: {}

          - Id: ALBOrigin
            DomainName:
              Ref: ALBDomainName
            CustomOriginConfig:
              HTTPSPort: 443
              OriginProtocolPolicy: https-only
            OriginCustomHeaders:
              - HeaderName: X-From-CloudFront
                HeaderValue: "true"

        DefaultCacheBehavior:
          TargetOriginId: ALBOrigin
          ViewerProtocolPolicy: redirect-to-https
          AllowedMethods:
            - GET
            - HEAD
            - OPTIONS
            - POST
          CachedMethods:
            - GET
            - HEAD
          ForwardedValues:
            QueryString: true
            Cookies:
              Forward: all

        CacheBehaviors:
          - PathPattern: "/static/*"
            TargetOriginId: S3Origin
            ViewerProtocolPolicy: redirect-to-https
            AllowedMethods:
              - GET
              - HEAD
            CachedMethods:
              - GET
              - HEAD
            ForwardedValues:
              QueryString: false
              Cookies:
                Forward: none

        ViewerCertificate:
          AcmCertificateArn:
            Ref: CertificateARN
          SslSupportMethod: sni-only
          MinimumProtocolVersion: TLSv1.2_2021

        WebACLId:
          Ref: WebACL

  CloudFrontDNS:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId:
        Ref: HostedZoneId
      Name:
        Ref: DomainName
      Type: A
      AliasTarget:
        DNSName:
          Fn::GetAtt:
            - CloudFrontDistribution
            - DomainName
        HostedZoneId: Z2FDTNDATAQYW2

Outputs:
  CloudFrontDomainName:
    Value:
      Fn::GetAtt:
        - CloudFrontDistribution
        - DomainName

  StaticBucketName:
    Value:
      Ref: StaticContentBucket
