AWSTemplateFormatVersion: "2010-09-09"
Description: Edge Layer - CloudFront com foco em Backend Java e S3

Parameters:
  Environment: { Type: String }
  ProjectName: { Type: String }
  DomainName: { Type: String }
  HostedZoneId: { Type: String }
  ALBDomainName: { Type: String }
  CertificateARN: { Type: String }

Resources:
  StaticContentBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${ProjectName}-${Environment}-${AWS::AccountId}-static-assets"
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

  CloudFrontOAC:
    Type: AWS::CloudFront::OriginAccessControl
    Properties:
      OriginAccessControlConfig:
        Name: !Sub "${ProjectName}-${Environment}-oac"
        OriginAccessControlOriginType: s3
        SigningBehavior: always
        SigningProtocol: sigv4

  WebACL:
    Type: AWS::WAFv2::WebACL
    Properties:
      Name: !Sub "${ProjectName}-${Environment}-waf"
      Scope: CLOUDFRONT
      DefaultAction: { Allow: {} }
      VisibilityConfig:
        SampledRequestsEnabled: true
        CloudWatchMetricsEnabled: true
        MetricName: waf
      Rules:
        - Name: AWSManagedRulesCommonRuleSet
          Priority: 1
          OverrideAction: { None: {} }
          Statement:
            ManagedRuleGroupStatement:
              VendorName: AWS
              Name: AWSManagedRulesCommonRuleSet
          VisibilityConfig:
            SampledRequestsEnabled: true
            CloudWatchMetricsEnabled: true
            MetricName: common

  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Enabled: true
        Aliases: [ !Ref DomainName ]
        Origins:
          - Id: S3Origin
            DomainName: !GetAtt StaticContentBucket.RegionalDomainName
            OriginAccessControlId: !Ref CloudFrontOAC
            S3OriginConfig: {}
          - Id: ALBOrigin
            DomainName: !Ref ALBDomainName
            CustomOriginConfig:
              OriginProtocolPolicy: https-only
              OriginSSLProtocols: [ TLSv1.2 ]

        DefaultCacheBehavior:
          TargetOriginId: ALBOrigin
          ViewerProtocolPolicy: redirect-to-https
          AllowedMethods: [ GET, HEAD, OPTIONS, POST, PUT, PATCH, DELETE ]
          CachedMethods: [ GET, HEAD ]
          ForwardedValues:
            QueryString: true
            Cookies: { Forward: all }
            Headers: [ "Authorization", "Host", "Origin", "Access-Control-Request-Headers", "Access-Control-Request-Method" ]
          # AJUSTE PARA BACKEND: Força o CloudFront a não cachear respostas da API
          MinTTL: 0
          DefaultTTL: 0
          MaxTTL: 0

        ViewerCertificate:
          AcmCertificateArn: !Ref CertificateARN
          SslSupportMethod: sni-only
          MinimumProtocolVersion: TLSv1.2_2021
        WebACLId: !GetAtt WebACL.Arn
        HttpVersion: http2
        PriceClass: PriceClass_100

Outputs:
  CloudFrontDNS:
    Value: !GetAtt CloudFrontDistribution.DomainName
  CloudFrontHostedZoneId:
    Value: Z2FDTNDATAQYW2