AWSTemplateFormatVersion: "2010-09-09"
Description: Edge Layer - CloudFront, S3, WAF e SSL via Parâmetro

Parameters:
  Environment:
    Type: String

  ProjectName:
    Type: String

  DomainName:
    Type: String
    Description: "Domain alias for CloudFront (must be covered by the ACM certificate)"

  HostedZoneId:
    Type: String

  ALBDomainName:
    Type: String
    Description: "DNS name of the Application Load Balancer (without protocol)"

  CertificateARN:
    Type: String
    Description: "ACM certificate ARN (must be in us-east-1)"

Resources:

  StaticContentBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${ProjectName}-${Environment}-static-assets"
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

  CloudFrontOAC:
    Type: AWS::CloudFront::OriginAccessControl
    Properties:
      OriginAccessControlConfig:
        Name: !Sub "${ProjectName}-${Environment}-oac"
        OriginAccessControlOriginType: s3
        SigningBehavior: always
        SigningProtocol: sigv4

  WebACL:
    Type: AWS::WAFv2::WebACL
    Properties:
      Name: !Sub "${ProjectName}-${Environment}-waf"
      Scope: CLOUDFRONT
      DefaultAction:
        Allow: {}
      VisibilityConfig:
        SampledRequestsEnabled: true
        CloudWatchMetricsEnabled: true
        MetricName: waf
      Rules:
        - Name: AWSManagedRulesCommonRuleSet
          Priority: 1
          OverrideAction:
            None: {}
          Statement:
            ManagedRuleGroupStatement:
              VendorName: AWS
              Name: AWSManagedRulesCommonRuleSet
          VisibilityConfig:
            SampledRequestsEnabled: true
            CloudWatchMetricsEnabled: true
            MetricName: common

  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Enabled: true

        Aliases:
          - !Ref DomainName

        Origins:
          # S3 Origin (Static Assets)
          - Id: S3Origin
            DomainName: !GetAtt StaticContentBucket.RegionalDomainName
            OriginAccessControlId: !Ref CloudFrontOAC
            S3OriginConfig: {}

          # ALB Origin (Backend)
          - Id: ALBOrigin
            DomainName: !Ref ALBDomainName
            CustomOriginConfig:
              OriginProtocolPolicy: https-only
              OriginSSLProtocols:
                - TLSv1.2

        DefaultCacheBehavior:
          TargetOriginId: ALBOrigin
          ViewerProtocolPolicy: redirect-to-https
          AllowedMethods:
            - GET
            - HEAD
            - OPTIONS
            - POST
            - PUT
            - PATCH
            - DELETE
          CachedMethods:
            - GET
            - HEAD
          ForwardedValues:
            QueryString: true
            Cookies:
              Forward: all

        ViewerCertificate:
          AcmCertificateArn: !Ref CertificateARN
          SslSupportMethod: sni-only
          MinimumProtocolVersion: TLSv1.2_2021

        WebACLId: !GetAtt WebACL.Arn

        HttpVersion: http2
        PriceClass: PriceClass_100

Outputs:
  CloudFrontDomainName:
    Description: "CloudFront distribution domain name"
    Value: !GetAtt CloudFrontDistribution.DomainName

  CloudFrontHostedZoneId:
    Description: "Hosted Zone ID for CloudFront (Route53 Alias)"
    Value: Z2FDTNDATAQYW2
