AWSTemplateFormatVersion: "2010-09-09"
Description: EFS for Application Tier (Multi-AZ) - Corrigido

Parameters:
  Environment: { Type: String, AllowedValues: [dev, prod] }
  ProjectName: { Type: String }
  VpcId: { Type: AWS::EC2::VPC::Id }
  # Mantido como String para aceitar o Join da Master Stack
  PrivateAppSubnets: { Type: String } 
  AppSecurityGroupId: { Type: AWS::EC2::SecurityGroup::Id }

Resources:
  EFSSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow NFS access from App Tier
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 2049
          ToPort: 2049
          SourceSecurityGroupId: !Ref AppSecurityGroupId
      Tags:
        - Key: Name
          Value: !Sub "${ProjectName}-${Environment}-efs-sg"

  FileSystem:
    Type: AWS::EFS::FileSystem
    Properties:
      Encrypted: true
      PerformanceMode: generalPurpose
      ThroughputMode: bursting
      BackupPolicy: { Status: ENABLED }
      FileSystemTags:
        - Key: Name
          Value: !Sub "${ProjectName}-${Environment}-efs"

  # Ajuste cirúrgico: Split transforma a string de subnets em lista para o Select
  MountTargetAZ1:
    Type: AWS::EFS::MountTarget
    Properties:
      FileSystemId: !Ref FileSystem
      SubnetId: !Select [ 0, !Split [ ",", !Ref PrivateAppSubnets ] ]
      SecurityGroups: [ !Ref EFSSecurityGroup ]

  MountTargetAZ2:
    Type: AWS::EFS::MountTarget
    Properties:
      FileSystemId: !Ref FileSystem
      SubnetId: !Select [ 1, !Split [ ",", !Ref PrivateAppSubnets ] ]
      SecurityGroups: [ !Ref EFSSecurityGroup ]

Outputs:
  FileSystemId:
    Value: !Ref FileSystem
    Export:
      Name: !Sub "${ProjectName}-${Environment}-FileSystemId"