AWSTemplateFormatVersion: "2010-09-09"
Description: ElastiCache Redis

Parameters:
  ProjectName: { Type: String }
  Environment: { Type: String }
  CacheNodeType: { Type: String, Default: cache.t3.micro }

Resources:
  RedisSubnetGroup:
    Type: AWS::ElastiCache::SubnetGroup
    Properties:
      Description: Subnets para Redis
      SubnetIds:
        - Fn::ImportValue: !Sub "${ProjectName}-vpc-${Environment}-private-app-az1"
        - Fn::ImportValue: !Sub "${ProjectName}-vpc-${Environment}-private-app-az2"

  RedisSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Acesso Redis
      VpcId: { Fn::ImportValue: !Sub "${ProjectName}-vpc-${Environment}-id" }
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 6379
          ToPort: 6379
          SourceSecurityGroupId: { Fn::ImportValue: !Sub "${ProjectName}-${Environment}-AppSG" }

  RedisCluster:
    Type: AWS::ElastiCache::CacheCluster
    Properties:
      Engine: redis
      CacheNodeType: !Ref CacheNodeType
      NumCacheNodes: 1
      VpcSecurityGroupIds: [ !GetAtt RedisSecurityGroup.GroupId ]
      CacheSubnetGroupName: !Ref RedisSubnetGroup
      Port: 6379

Outputs:
  RedisEndpoint:
    Value: !GetAtt RedisCluster.RedisEndpoint.Address
    Export:
      Name: !Sub "${ProjectName}-${Environment}-RedisEndpoint"