AWSTemplateFormatVersion: "2010-09-09"
Description: Módulo de Identidade - Roles e Permissões para EC2, SSM e CodeDeploy

Parameters:
  ProjectName:
    Type: String
  Environment:
    Type: String

Resources:
  # 1. A ROLE (Identidade da EC2)
  AppInstanceRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "${ProjectName}-${Environment}-app-role"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole

      ManagedPolicyArns:
        # Faz a instância virar "Managed: true" no SSM
        - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore

        # Permite que o CodeDeploy registre e controle a instância
        - arn:aws:iam::aws:policy/service-role/AWSCodeDeployRole

        # Permite baixar artefatos do S3
        - arn:aws:iam::aws:policy/AmazonS3ReadOnlyAccess

        # Permite envio de logs e métricas para o CloudWatch
        - arn:aws:iam::aws:policy/CloudWatchAgentServerPolicy

  # 2. INSTANCE PROFILE (O "adaptador" entre a Role e a EC2)
  AppInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      InstanceProfileName: !Sub "${ProjectName}-${Environment}-app-profile"
      Roles:
        - !Ref AppInstanceRole

Outputs:
  # Este é o valor que o ASG vai importar
  AppInstanceProfileName:
    Description: Instance Profile da aplicação para EC2 / ASG
    Value: !Ref AppInstanceProfile
    Export:
      Name: !Sub "${ProjectName}-${Environment}-AppInstanceProfile"
