AWSTemplateFormatVersion: "2010-09-09"
Description: Módulo de Identidade - Roles e Permissões para EC2, SSM e CodeDeploy

Parameters:
  ProjectName:
    Type: String
  Environment:
    Type: String

Resources:
  # 1. A ROLE (Identidade da EC2)
  AppInstanceRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "${ProjectName}-${Environment}-app-role"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole

      ManagedPolicyArns:
        # Resolve o "Managed: False" permitindo comunicação com Systems Manager [cite: 2025-12-19]
        - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
        # Necessário para o Agente do CodeDeploy na instância [cite: 2025-12-19]
        - arn:aws:iam::aws:policy/service-role/AWSCodeDeployRole
        # Permite envio de logs para o CloudWatch [cite: 2025-12-19]
        - arn:aws:iam::aws:policy/CloudWatchAgentServerPolicy

      Policies:
        - PolicyName: S3ArtifactsAccess
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:GetObjectVersion
                  - s3:ListBucket
                Resource: 
                  # Permissão específica para o seu bucket de artefatos [cite: 2025-12-19]
                  - arn:aws:s3:::stock-manager-prod-artifacts
                  - arn:aws:s3:::stock-manager-prod-artifacts/*

  # 2. INSTANCE PROFILE (O "adaptador" entre a Role e a EC2)
  AppInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      # O !Ref aqui retorna o NOME do profile, que é o que o ASG precisa [cite: 2025-12-19]
      InstanceProfileName: !Sub "${ProjectName}-${Environment}-app-profile"
      Roles:
        - !Ref AppInstanceRole

Outputs:
  AppInstanceProfileName:
    Description: Nome do Instance Profile para exportação
    Value: !Ref AppInstanceProfile
    Export:
      Name: !Sub "${ProjectName}-${Environment}-AppInstanceProfile"


      
