AWSTemplateFormatVersion: "2010-09-09"
Description: Módulo de Banco de Dados - Aurora PostgreSQL (Versão Final Estável)

Parameters:
  ProjectName:
    Type: String
  Environment:
    Type: String
  DBUsername:
    Type: String
    Default: dbadmin
  DBPassword:
    Type: String
    NoEcho: true
  DBName:
    Type: String
    Default: stockmanagerprod
  DBInstanceClass:
    Type: String
    Default: db.t3.medium

Resources:
  DBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: Subnets privadas para Aurora PostgreSQL
      SubnetIds:
        - Fn::ImportValue: !Sub "${ProjectName}-vpc-${Environment}-private-db-az1"
        - Fn::ImportValue: !Sub "${ProjectName}-vpc-${Environment}-private-db-az2"

  DBCluster:
    Type: AWS::RDS::DBCluster
    Properties:
      Engine: aurora-postgresql
      EngineVersion: "15.4" 
      DatabaseName: !Ref DBName
      MasterUsername: !Ref DBUsername
      MasterUserPassword: !Ref DBPassword
      DBSubnetGroupName: !Ref DBSubnetGroup
      VpcSecurityGroupIds:
        - Fn::ImportValue: !Sub "${ProjectName}-${Environment}-DbSG"
      BackupRetentionPeriod: 7
      StorageEncrypted: true
      DeletionProtection: false

  DBInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      Engine: aurora-postgresql
      EngineVersion: "15.4" 
      DBClusterIdentifier: !Ref DBCluster
      DBInstanceClass: !Ref DBInstanceClass
      PubliclyAccessible: false

Outputs:
  DBEndpoint:
    Description: Endpoint do Cluster Aurora
    Value: !GetAtt DBCluster.Endpoint.Address
    Export:
      Name: !Sub "${ProjectName}-${Environment}-DBEndpoint"