AWSTemplateFormatVersion: "2010-09-09"
Description: RDS PostgreSQL - Camada de Dados Segura e Privada (Sem vínculos com ALB App)

Parameters:
  Environment: { Type: String }
  VpcId: { Type: AWS::EC2::VPC::Id }
  DBName: { Type: String, Default: stockmanager }
  DBUsername: { Type: String }
  DBPassword: { Type: String, NoEcho: true }
  # Alterado para t3.micro com fallback para resolver o erro da sua imagem
  DBInstanceClass: { Type: String, Default: db.t4g.micro } 
  PrivateSubnetA: { Type: AWS::EC2::Subnet::Id }
  PrivateSubnetB: { Type: AWS::EC2::Subnet::Id }
  AppSecurityGroupId: { Type: String } 

Conditions:
  IsProd: { Fn::Equals: [{ Ref: Environment }, prod] }

Resources:
  # Security Group exclusivo para o RDS (Boa prática de segurança)
  RDSSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: !Sub "Acesso ao Postgres vindo da App - ${Environment}"
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 5432
          ToPort: 5432
          SourceSecurityGroupId: !Ref AppSecurityGroupId

  DBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: "Subnets privadas exclusivas para o banco de dados"
      SubnetIds: 
        - !Ref PrivateSubnetA
        - !Ref PrivateSubnetB

  RDSInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      DBInstanceIdentifier: !Sub "stock-manager-${Environment}-db"
      Engine: postgres
      EngineVersion: "15.7"
      DBInstanceClass: !Ref DBInstanceClass
      AllocatedStorage: 20
      DBName: !Ref DBName
      MasterUsername: !Ref DBUsername
      MasterUserPassword: !Ref DBPassword
      # Agora usa o SG específico criado acima
      VPCSecurityGroups: 
        - !Ref RDSSecurityGroup 
      DBSubnetGroupName: !Ref DBSubnetGroup
      MultiAZ: !If [IsProd, true, false]
      PubliclyAccessible: false
      DeletionProtection: false 

Outputs:
  RDSHost:
    Description: "Endpoint de conexão do banco de dados"
    Value: !GetAtt RDSInstance.Endpoint.Address