AWSTemplateFormatVersion: "2010-09-09"
Description: Modulo RDS Aurora PostgreSQL

Parameters:
  ProjectName:
    Type: String

  Environment:
    Type: String

  DBUsername:
    Type: String

  DBPassword:
    Type: String
    NoEcho: true

  DBName:
    Type: String

  DBInstanceClass:
    Type: String

Resources:

  DBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: Subnets privadas para Aurora PostgreSQL
      SubnetIds:
        - Fn::ImportValue: !Sub "${ProjectName}-vpc-${Environment}-private-db-az1"
        - Fn::ImportValue: !Sub "${ProjectName}-vpc-${Environment}-private-db-az2"

  DBCluster:
    Type: AWS::RDS::DBCluster
    Properties:
      DBClusterIdentifier: !Sub "${ProjectName}-${Environment}-aurora-cluster"
      Engine: aurora-postgresql
      EngineVersion: "15.4"
      DatabaseName: !Ref DBName
      MasterUsername: !Ref DBUsername
      MasterUserPassword: !Ref DBPassword
      DBSubnetGroupName: !Ref DBSubnetGroup
      VpcSecurityGroupIds:
        - Fn::ImportValue: !Sub "${ProjectName}-${Environment}-DbSG"
      BackupRetentionPeriod: 7
      StorageEncrypted: true
      DeletionProtection: false

  DBInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      DBClusterIdentifier: !Ref DBCluster
      DBInstanceClass: !Ref DBInstanceClass
      Engine: aurora-postgresql
      EngineVersion: "15.4"
      PubliclyAccessible: false

Outputs:
  DBEndpoint:
    Description: Endpoint do Cluster Aurora
    Value: !GetAtt DBCluster.Endpoint.Address
    Export:
      Name: !Sub "${ProjectName}-${Environment}-DBEndpoint"
