AWSTemplateFormatVersion: "2010-09-09"
Description: Modulo RDS Aurora PostgreSQL

Parameters:
  ProjectName: { Type: String }
  Environment: { Type: String }
  DBUsername: { Type: String }
  DBPassword: { Type: String, NoEcho: true }
  DBName: { Type: String }
  DBInstanceClass: { Type: String }

Resources:
  DBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: Subnets privadas para Aurora
      SubnetIds:
        - Fn::ImportValue: !Sub "${ProjectName}-vpc-${Environment}-private-db-az1"
        - Fn::ImportValue: !Sub "${ProjectName}-vpc-${Environment}-private-db-az2"

  DBCluster:
    Type: AWS::RDS::DBCluster
    Properties:
      # ... (Mantenha as configurações de Engine e EngineVersion)
      DBSubnetGroupName: !Ref DBSubnetGroup
      VpcSecurityGroupIds:
        - Fn::ImportValue: !Sub "${ProjectName}-${Environment}-DbSG"
      StorageEncrypted: true

  DBInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      DBClusterIdentifier: !Ref DBCluster
      DBInstanceClass: !Ref DBInstanceClass
      Engine: aurora-postgresql
      EngineVersion: "15.8"

Outputs:
  DBEndpoint:
    Value: !GetAtt DBCluster.Endpoint.Address
    Export:
      Name: !Sub "${ProjectName}-${Environment}-DBEndpoint"