AWSTemplateFormatVersion: "2010-09-09"
Description: RDS PostgreSQL - Camada de Dados Segura e Privada

Parameters:
  Environment: { Type: String }
  VpcId: { Type: AWS::EC2::VPC::Id }
  DBName: { Type: String, Default: stockmanager }
  DBUsername: { Type: String }
  DBPassword: { Type: String, NoEcho: true }
  DBInstanceClass: { Type: String, Default: db.t3.micro }
  PrivateSubnetA: { Type: AWS::EC2::Subnet::Id }
  PrivateSubnetB: { Type: AWS::EC2::Subnet::Id }
  AppSecurityGroupId: { Type: String } # Recebe o ID do módulo de segurança

Conditions:
  IsProd: { Fn::Equals: [{ Ref: Environment }, prod] }

Resources:
  # --- Grupo de Subnets ---
  DBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: "Subnets privadas exclusivas para o banco de dados"
      SubnetIds: 
        - !Ref PrivateSubnetA
        - !Ref PrivateSubnetB

  # --- Instância do Banco de Dados ---
  RDSInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      DBInstanceIdentifier: !Sub "stock-manager-${Environment}"
      Engine: postgres
      EngineVersion: "15.7"
      DBInstanceClass: !Ref DBInstanceClass
      AllocatedStorage: 20
      DBName: !Ref DBName
      MasterUsername: !Ref DBUsername
      MasterUserPassword: !Ref DBPassword
      VPCSecurityGroups: 
        - !Ref AppSecurityGroupId # Sim: Agora usa o SG que permite acesso apenas da App
      DBSubnetGroupName: !Ref DBSubnetGroup
      MultiAZ: !If [IsProd, true, false]
      PubliclyAccessible: false
      DeletionProtection: false 

Outputs:
  RDSHost:
    Description: "Endpoint de conexão do banco de dados"
    Value: !GetAtt RDSInstance.Endpoint.Address