AWSTemplateFormatVersion: "2010-09-09"
Description: Módulo Route 53 - Apontando o Domínio para o CloudFront

Parameters:
  ProjectName: { Type: String }
  Environment: { Type: String }
  DomainName: { Type: String }
  # Sim: Este ID deve ser o que aparece no seu console AWS
  HostedZoneId: { Type: String }
  CloudFrontDNS: { Type: String }

Resources:
  # --- Registro DNS tipo Alias para CloudFront ---
  # Sim: Usamos o ID da zona que já existe para criar apenas o apontamento
  CloudFrontRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZoneId
      Name: !Ref DomainName
      Type: A
      AliasTarget:
        DNSName: !Ref CloudFrontDNS
        # Sim: ID fixo padrão da AWS para CloudFront
        HostedZoneId: Z2FDTNDATAQYW2
        EvaluateTargetHealth: false

Outputs:
  DomainURL:
    Description: "URL final do projeto"
    Value: !Sub "https://${DomainName}"