AWSTemplateFormatVersion: "2010-09-09"
Description: Módulo Route 53 - Isolado

Parameters:
  ParentStackName: { Type: String } # Nome da stack master vindo do GitHub
  DomainName: { Type: String }
  HostedZoneId: { Type: String }

Resources:
  CloudFrontRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZoneId
      Name: !Ref DomainName
      Type: A
      AliasTarget:
        # Ele lê o carimbo que o Job 1 (Master) deixou na conta AWS
        DNSName: !ImportValue 
          Fn::Sub: "${ParentStackName}-CF-DNS"
        HostedZoneId: Z2FDTNDATAQYW2
        EvaluateTargetHealth: false

Outputs:
  DomainURL:
    Description: "URL final do projeto"
    Value: !Sub "https://${DomainName}"
    
    