AWSTemplateFormatVersion: "2010-09-09"
Description: Módulo Route 53 - Importando DNS da Master Stack

Parameters:
  DomainName: 
    Type: String
  HostedZoneId: 
    Type: String
  ParentStackName: 
    Type: String
    Description: Nome da stack mestre para importar o DNS do CloudFront

Resources:
  CloudFrontRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZoneId
      Name: !Ref DomainName
      Type: A
      AliasTarget:
        # Importa automaticamente o DNS exportado pela Master Stack
        DNSName: !ImportValue 
          Fn::Sub: "${ParentStackName}-CF-DNS"
        HostedZoneId: Z2FDTNDATAQYW2
        EvaluateTargetHealth: false

Outputs:
  DomainURL:
    Description: "URL final do projeto"
    Value: !Sub "https://${DomainName}"
    
    