AWSTemplateFormatVersion: "2010-09-09"
Description: Central Security Groups - ALB, App e RDS

Parameters:
  VpcId:
    Type: AWS::EC2::VPC::Id
  ProjectName:
    Type: String
  Environment:
    Type: String

Resources:
  AlbWebSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Public ALB SG
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0

  AppSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: App SG
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 8080
          ToPort: 8080
          SourceSecurityGroupId: !Ref AlbWebSecurityGroup

  RDSSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: RDS SG
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 5432
          ToPort: 5432
          SourceSecurityGroupId: !Ref AppSecurityGroup

Outputs:
  AlbWebSecurityGroupId:
    Value: !Ref AlbWebSecurityGroup
    Export:
      Name: !Sub "${ProjectName}-${Environment}-AlbSG"

  AppSecurityGroupId:
    Value: !Ref AppSecurityGroup
    Export:
      Name: !Sub "${ProjectName}-${Environment}-AppSG"
