AWSTemplateFormatVersion: "2010-09-09"
Description: Security Groups base para aplicacao monolitica - Versao Final Sem Acentos

Parameters:
  ProjectName:
    Type: String
  Environment:
    Type: String
  VpcId:
    Type: String
    Description: ID da VPC vindo do modulo vpc.yaml

Resources:
  # Security Group para o Load Balancer
  AlbSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Permite trafego HTTP e HTTPS da Internet para o ALB
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: 0.0.0.0/0
      SecurityGroupEgress:
        - IpProtocol: -1
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: !Sub "${ProjectName}-${Environment}-alb-sg"

  # Security Group para a Instancia EC2
  AppSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Permite trafego apenas do ALB na porta 8080
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 8080
          ToPort: 8080
          SourceSecurityGroupId: !Ref AlbSecurityGroup
      SecurityGroupEgress:
        - IpProtocol: -1
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: !Sub "${ProjectName}-${Environment}-app-sg"

  # Security Group para o Banco de Dados (Sem regras inline)
  DbSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Container para as regras do Banco de Dados
      VpcId: !Ref VpcId
      SecurityGroupEgress:
        - IpProtocol: -1
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: !Sub "${ProjectName}-${Environment}-db-sg"

  # Regra de entrada separada para o RDS
  DbIngressFromApp:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      Description: Permite conexao PostgreSQL vinda das instancias da App
      GroupId: !Ref DbSecurityGroup
      IpProtocol: tcp
      FromPort: 5432
      ToPort: 5432
      SourceSecurityGroupId: !Ref AppSecurityGroup

Outputs:
  AlbSecurityGroup:
    Value: !Ref AlbSecurityGroup
    Export:
      Name: !Sub "${ProjectName}-${Environment}-AlbSG"
  AppSecurityGroup:
    Value: !Ref AppSecurityGroup
    Export:
      Name: !Sub "${ProjectName}-${Environment}-AppSG"
  DbSecurityGroup:
    Value: !Ref DbSecurityGroup
    Export:
      Name: !Sub "${ProjectName}-${Environment}-DbSG"