AWSTemplateFormatVersion: "2010-09-09"
Description: Security Groups base para aplicação monolítica

Parameters:
  ProjectName:
    Type: String
  Environment:
    Type: String
  VpcId:
    Type: String

Resources:
  AlbSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: ALB SG
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: !Sub "${ProjectName}-${Environment}-alb-sg"

  AppSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: App SG
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 8080
          ToPort: 8080
          SourceSecurityGroupId: !Ref AlbSecurityGroup
        # PERMITE ACESSO SSH/SSM SE NECESSÁRIO
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: !Sub "${ProjectName}-${Environment}-app-sg"

  DbSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: DB SG
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 5432
          ToPort: 5432
          SourceSecurityGroupId: !Ref AppSecurityGroup
        # REGRA DE OURO: Permite que a VPC fale com o banco (Resolve seu Timeout)
        - IpProtocol: tcp
          FromPort: 5432
          ToPort: 5432
          CidrIp: 10.0.0.0/16
      Tags:
        - Key: Name
          Value: !Sub "${ProjectName}-${Environment}-db-sg"

Outputs:
  AlbSecurityGroup:
    Value: !Ref AlbSecurityGroup
    Export: { Name: !Sub "${ProjectName}-${Environment}-AlbSG" }
  AppSecurityGroup:
    Value: !Ref AppSecurityGroup
    Export: { Name: !Sub "${ProjectName}-${Environment}-AppSG" }
  DbSecurityGroup:
    Value: !Ref DbSecurityGroup
    Export: { Name: !Sub "${ProjectName}-${Environment}-DbSG" }