AWSTemplateFormatVersion: "2010-09-09"
Description: VPC - Arquitetura monolítica com NAT Gateway para deploy em subnets privadas

Parameters:
  Environment:
    Type: String
    AllowedValues: [dev, prod]
  ProjectName:
    Type: String

Resources:

  # =========================
  # Infraestrutura de Rede Base
  # =========================
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: !Sub "${ProjectName}-${Environment}-vpc"

  InternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: !Sub "${ProjectName}-${Environment}-igw"

  AttachGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref VPC
      InternetGatewayId: !Ref InternetGateway

  # =========================
  # NAT Gateway (Saída para Internet das Privadas)
  # =========================
  NatEip:
    Type: AWS::EC2::EIP
    Properties:
      Domain: vpc
      Tags:
        - Key: Name
          Value: !Sub "${ProjectName}-${Environment}-nat-eip"

  NatGateway:
    Type: AWS::EC2::NatGateway
    Properties:
      AllocationId: !GetAtt NatEip.AllocationId
      SubnetId: !Ref PublicSubnetAZ1
      Tags:
        - Key: Name
          Value: !Sub "${ProjectName}-${Environment}-nat-gw"

  # =========================
  # Subnets Públicas
  # =========================
  PublicSubnetAZ1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      AvailabilityZone: !Select [0, !GetAZs ""]
      CidrBlock: 10.0.1.0/24
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: !Sub "${ProjectName}-${Environment}-pub-az1"

  PublicSubnetAZ2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      AvailabilityZone: !Select [1, !GetAZs ""]
      CidrBlock: 10.0.2.0/24
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: !Sub "${ProjectName}-${Environment}-pub-az2"

  # =========================
  # Subnets Privadas (APP/Backend)
  # =========================
  PrivateAppAZ1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      AvailabilityZone: !Select [0, !GetAZs ""]
      CidrBlock: 10.0.21.0/24
      Tags:
        - Key: Name
          Value: !Sub "${ProjectName}-${Environment}-app-priv-az1"

  PrivateAppAZ2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      AvailabilityZone: !Select [1, !GetAZs ""]
      CidrBlock: 10.0.22.0/24
      Tags:
        - Key: Name
          Value: !Sub "${ProjectName}-${Environment}-app-priv-az2"

  # =========================
  # Tabelas de Rota
  # =========================
  PublicRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: !Sub "${ProjectName}-${Environment}-pub-rt"

  PublicRoute:
    Type: AWS::EC2::Route
    DependsOn: AttachGateway
    Properties:
      RouteTableId: !Ref PublicRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref InternetGateway

  PrivateRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: !Sub "${ProjectName}-${Environment}-priv-rt"

  PrivateRoute:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref PrivateRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      NatGatewayId: !Ref NatGateway

  # =========================
  # Associações (Vincula Subnets às Rotas)
  # =========================
  PublicAssoc1:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PublicSubnetAZ1
      RouteTableId: !Ref PublicRouteTable

  PublicAssoc2:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PublicSubnetAZ2
      RouteTableId: !Ref PublicRouteTable

  AppAssoc1:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PrivateAppAZ1
      RouteTableId: !Ref PrivateRouteTable

  AppAssoc2:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PrivateAppAZ2
      RouteTableId: !Ref PrivateRouteTable

Outputs:
  VpcId:
    Value: !Ref VPC
    Export:
      Name: !Sub "${ProjectName}-vpc-${Environment}-id"

  PublicSubnetAZ1:
    Value: !Ref PublicSubnetAZ1
    Export:
      Name: !Sub "${ProjectName}-vpc-${Environment}-public-az1"

  PublicSubnetAZ2:
    Value: !Ref PublicSubnetAZ2
    Export:
      Name: !Sub "${ProjectName}-vpc-${Environment}-public-az2"

  PrivateAppSubnetAZ1:
    Value: !Ref PrivateAppAZ1
    Export:
      Name: !Sub "${ProjectName}-vpc-${Environment}-private-app-az1"

  PrivateAppSubnetAZ2:
    Value: !Ref PrivateAppAZ2
    Export:
      Name: !Sub "${ProjectName}-vpc-${Environment}-private-app-az2"

  
  
