AWSTemplateFormatVersion: "2010-09-09"
Description: VPC - Arquitetura monolítica com subnets públicas e privadas (corrigida)

Parameters:
  Environment:
    Type: String
    AllowedValues: [dev, prod]

  ProjectName:
    Type: String

Resources:

  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: !Sub "${ProjectName}-${Environment}-vpc"

  InternetGateway:
    Type: AWS::EC2::InternetGateway

  AttachGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref VPC
      InternetGatewayId: !Ref InternetGateway

  # -------------------------
  # Subnets Públicas
  # -------------------------
  PublicSubnetAZ1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      AvailabilityZone: !Select [0, !GetAZs ""]
      CidrBlock: 10.0.1.0/24
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: !Sub "${ProjectName}-${Environment}-public-az1"

  PublicSubnetAZ2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      AvailabilityZone: !Select [1, !GetAZs ""]
      CidrBlock: 10.0.2.0/24
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: !Sub "${ProjectName}-${Environment}-public-az2"

  # -------------------------
  # Subnets Privadas - WEB
  # -------------------------
  PrivateWebAZ1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      AvailabilityZone: !Select [0, !GetAZs ""]
      CidrBlock: 10.0.11.0/24
      MapPublicIpOnLaunch: false
      Tags:
        - Key: Name
          Value: !Sub "${ProjectName}-${Environment}-private-web-az1"

  PrivateWebAZ2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      AvailabilityZone: !Select [1, !GetAZs ""]
      CidrBlock: 10.0.12.0/24
      MapPublicIpOnLaunch: false
      Tags:
        - Key: Name
          Value: !Sub "${ProjectName}-${Environment}-private-web-az2"

  # -------------------------
  # Subnets Privadas - APP
  # -------------------------
  PrivateAppAZ1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      AvailabilityZone: !Select [0, !GetAZs ""]
      CidrBlock: 10.0.21.0/24
      MapPublicIpOnLaunch: false
      Tags:
        - Key: Name
          Value: !Sub "${ProjectName}-${Environment}-private-app-az1"

  PrivateAppAZ2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      AvailabilityZone: !Select [1, !GetAZs ""]
      CidrBlock: 10.0.22.0/24
      MapPublicIpOnLaunch: false
      Tags:
        - Key: Name
          Value: !Sub "${ProjectName}-${Environment}-private-app-az2"

  # -------------------------
  # Subnets Privadas - DB
  # -------------------------
  PrivateDbAZ1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      AvailabilityZone: !Select [0, !GetAZs ""]
      CidrBlock: 10.0.31.0/24
      MapPublicIpOnLaunch: false
      Tags:
        - Key: Name
          Value: !Sub "${ProjectName}-${Environment}-private-db-az1"

  PrivateDbAZ2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      AvailabilityZone: !Select [1, !GetAZs ""]
      CidrBlock: 10.0.32.0/24
      MapPublicIpOnLaunch: false
      Tags:
        - Key: Name
          Value: !Sub "${ProjectName}-${Environment}-private-db-az2"

  # -------------------------
  # NAT Gateway
  # -------------------------
  NatEip:
    Type: AWS::EC2::EIP
    Properties:
      Domain: vpc

  NatGateway:
    Type: AWS::EC2::NatGateway
    Properties:
      AllocationId: !GetAtt NatEip.AllocationId
      SubnetId: !Ref PublicSubnetAZ1

  # -------------------------
  # Route Tables
  # -------------------------
  PublicRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC

  PublicRoute:
    Type: AWS::EC2::Route
    DependsOn: AttachGateway
    Properties:
      RouteTableId: !Ref PublicRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref InternetGateway

  PrivateRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC

  PrivateRoute:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref PrivateRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      NatGatewayId: !Ref NatGateway

  # -------------------------
  # Associations
  # -------------------------
  PublicAssoc1:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PublicSubnetAZ1
      RouteTableId: !Ref PublicRouteTable

  PublicAssoc2:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PublicSubnetAZ2
      RouteTableId: !Ref PublicRouteTable

  PrivateAssocWeb1:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PrivateWebAZ1
      RouteTableId: !Ref PrivateRouteTable

  PrivateAssocWeb2:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PrivateWebAZ2
      RouteTableId: !Ref PrivateRouteTable

  PrivateAssocApp1:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PrivateAppAZ1
      RouteTableId: !Ref PrivateRouteTable

  PrivateAssocApp2:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PrivateAppAZ2
      RouteTableId: !Ref PrivateRouteTable

  PrivateAssocDb1:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PrivateDbAZ1
      RouteTableId: !Ref PrivateRouteTable

  PrivateAssocDb2:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PrivateDbAZ2
      RouteTableId: !Ref PrivateRouteTable
      
Outputs:

  VpcId:
    Value: !Ref VPC
    Export:
      Name: !Sub "${ProjectName}-vpc-${Environment}-id"

  PublicSubnetAz1:
    Value: !Ref PublicSubnetAZ1
    Export:
      Name: !Sub "${ProjectName}-vpc-${Environment}-public-az1"

  PublicSubnetAz2:
    Value: !Ref PublicSubnetAZ2
    Export:
      Name: !Sub "${ProjectName}-vpc-${Environment}-public-az2"

  PrivateWebSubnetAz1:
    Value: !Ref PrivateWebAZ1
    Export:
      Name: !Sub "${ProjectName}-vpc-${Environment}-private-web-az1"

  PrivateWebSubnetAz2:
    Value: !Ref PrivateWebAZ2
    Export:
      Name: !Sub "${ProjectName}-vpc-${Environment}-private-web-az2"

  PrivateAppSubnetAz1:
    Value: !Ref PrivateAppAZ1
    Export:
      Name: !Sub "${ProjectName}-vpc-${Environment}-private-app-az1"

  PrivateAppSubnetAz2:
    Value: !Ref PrivateAppAZ2
    Export:
      Name: !Sub "${ProjectName}-vpc-${Environment}-private-app-az2"

  PrivateDbSubnetAz1:
    Value: !Ref PrivateDbAZ1
    Export:
      Name: !Sub "${ProjectName}-vpc-${Environment}-private-db-az1"

  PrivateDbSubnetAz2:
    Value: !Ref PrivateDbAZ2
    Export:
      Name: !Sub "${ProjectName}-vpc-${Environment}-private-db-az2"
   

  
  
  
