AWSTemplateFormatVersion: "2010-09-09"
Description: WAF v2 associado ao CloudFront (proteção L7 básica)

Parameters:
  ProjectName:
    Type: String

  Environment:
    Type: String

Resources:

  # ==================================================
  # Web ACL do WAF
  # ==================================================
  CloudFrontWebACL:
    Type: AWS::WAFv2::WebACL
    Properties:
      Name: !Sub "${ProjectName}-${Environment}-cloudfront-waf"
      Scope: CLOUDFRONT
      DefaultAction:
        Allow: {}
      VisibilityConfig:
        CloudWatchMetricsEnabled: true
        MetricName: !Sub "${ProjectName}-${Environment}-waf"
        SampledRequestsEnabled: true

      Rules:
        # Proteção contra SQL Injection
        - Name: AWS-AWSManagedRulesSQLiRuleSet
          Priority: 1
          OverrideAction:
            None: {}
          Statement:
            ManagedRuleGroupStatement:
              VendorName: AWS
              Name: AWSManagedRulesSQLiRuleSet
          VisibilityConfig:
            CloudWatchMetricsEnabled: true
            MetricName: SQLi
            SampledRequestsEnabled: true

        # Proteção contra XSS + ataques comuns
        - Name: AWS-AWSManagedRulesCommonRuleSet
          Priority: 2
          OverrideAction:
            None: {}
          Statement:
            ManagedRuleGroupStatement:
              VendorName: AWS
              Name: AWSManagedRulesCommonRuleSet
          VisibilityConfig:
            CloudWatchMetricsEnabled: true
            MetricName: CommonRules
            SampledRequestsEnabled: true

  # ==================================================
  # Associação do WAF ao CloudFront
  # ==================================================
  CloudFrontWebACLAssociation:
    Type: AWS::WAFv2::WebACLAssociation
    Properties:
      ResourceArn:
        Fn::ImportValue: !Sub "${ProjectName}-${Environment}-CloudFrontDistributionId"
      WebACLArn: !GetAtt CloudFrontWebACL.Arn

Outputs:
  WebACLArn:
    Description: ARN do WAF associado ao CloudFront
    Value: !GetAtt CloudFrontWebACL.Arn
    Export:
      Name: !Sub "${ProjectName}-${Environment}-WafArn"
