AWSTemplateFormatVersion: "2010-09-09"
Description: WAF v2 para CloudFront (proteção L7 básica)

Parameters:
  ProjectName:
    Type: String
  Environment:
    Type: String

Resources:
  # ==================================================
  # Web ACL do WAF (Obrigatório em us-east-1 para CloudFront)
  # ==================================================
  CloudFrontWebACL:
    Type: AWS::WAFv2::WebACL
    Properties:
      Name: !Sub "${ProjectName}-${Environment}-waf"
      Scope: CLOUDFRONT
      DefaultAction:
        Allow: {}
      VisibilityConfig:
        CloudWatchMetricsEnabled: true
        MetricName: !Sub "${ProjectName}${Environment}WafMetrics"
        SampledRequestsEnabled: true
      Rules:
        # Proteção contra SQL Injection (Protege seu Banco de Dados)
        - Name: AWS-AWSManagedRulesSQLiRuleSet
          Priority: 1
          OverrideAction:
            None: {}
          Statement:
            ManagedRuleGroupStatement:
              VendorName: AWS
              Name: AWSManagedRulesSQLiRuleSet
          VisibilityConfig:
            CloudWatchMetricsEnabled: true
            MetricName: SQLiRule
            SampledRequestsEnabled: true

        # Proteção contra ataques comuns (OWASP Top 10)
        - Name: AWS-AWSManagedRulesCommonRuleSet
          Priority: 2
          OverrideAction:
            None: {}
          Statement:
            ManagedRuleGroupStatement:
              VendorName: AWS
              Name: AWSManagedRulesCommonRuleSet
          VisibilityConfig:
            CloudWatchMetricsEnabled: true
            MetricName: CommonRule
            SampledRequestsEnabled: true

Outputs:
  WebACLArn:
    Description: ARN do WAF para o CloudFront
    Value: !GetAtt CloudFrontWebACL.Arn
    Export:
      Name: !Sub "${ProjectName}-${Environment}-WafArn"