AWSTemplateFormatVersion: "2010-09-09"
Description: Master do Job 3 - Compute (ASG + CodeDeploy)
Parameters:
  ProjectName:
    Type: String
  Environment:
    Type: String
    AllowedValues: [dev, prod]
  ArtifactsBucket:
    Type: String
  AmiId:
    Type: AWS::EC2::Image::Id
  InstanceType:
    Type: String
  KeyPairName:
    Type: AWS::EC2::KeyPair::KeyName
  DBUsername:
    Type: String
  DBPassword:
    Type: String
    NoEcho: true
  DBName:
    Type: String
    Default: stockmanagerprod

Resources:
  # =========================
  # AUTO SCALING GROUP STACK
  # =========================
  AsgStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "https://${ArtifactsBucket}.s3.amazonaws.com/modules/asg.yaml"
      Parameters:
        ProjectName: !Ref ProjectName
        Environment: !Ref Environment
        AmiId: !Ref AmiId
        InstanceType: !Ref InstanceType
        KeyPairName: !Ref KeyPairName
        DBUsername: !Ref DBUsername
        DBPassword: !Ref DBPassword
        DBName: !Ref DBName

  # =========================
  # CODEDEPLOY STACK
  # =========================
  CodeDeployStack:
    Type: AWS::CloudFormation::Stack
    DependsOn:
      - AsgStack
    Properties:
      TemplateURL: !Sub "https://${ArtifactsBucket}.s3.amazonaws.com/modules/codedeploy.yaml"
      Parameters:
        ProjectName: !Ref ProjectName
        Environment: !Ref Environment
        AsgName: !GetAtt AsgStack.Outputs.AutoScalingGroupName

