AWSTemplateFormatVersion: "2010-09-09"
Description: Core Stack - ALB, RDS, Redis, EFS, WAF e CloudFront

Parameters:
  ProjectName:
    Type: String
  Environment:
    Type: String
  ArtifactsBucket:
    Type: String
  CertificateARN:
    Type: String
  DomainName:
    Type: String
  DBUsername:
    Type: String
  DBPassword:
    Type: String
    NoEcho: true
  DBName:
    Type: String
  DBInstanceClass:
    Type: String

Resources:
  WafStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "https://${ArtifactsBucket}.s3.amazonaws.com/modules/waf-cloudfront.yaml"
      Parameters:
        ProjectName: !Ref ProjectName
        Environment: !Ref Environment

  AlbStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "https://${ArtifactsBucket}.s3.amazonaws.com/modules/alb.yaml"
      Parameters:
        ProjectName: !Ref ProjectName
        Environment: !Ref Environment
        CertificateARN: !Ref CertificateARN

  RdsStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: AlbStack
    Properties:
      TemplateURL: !Sub "https://${ArtifactsBucket}.s3.amazonaws.com/modules/rds.yaml"
      Parameters:
        ProjectName: !Ref ProjectName
        Environment: !Ref Environment
        DBUsername: !Ref DBUsername
        DBPassword: !Ref DBPassword
        DBName: !Ref DBName
        DBInstanceClass: !Ref DBInstanceClass

  RedisStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "https://${ArtifactsBucket}.s3.amazonaws.com/modules/elasticache.yaml"
      Parameters:
        ProjectName: !Ref ProjectName
        Environment: !Ref Environment

  EfsStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "https://${ArtifactsBucket}.s3.amazonaws.com/modules/efs.yaml"
      Parameters:
        ProjectName: !Ref ProjectName
        Environment: !Ref Environment

  CloudFrontStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: [AlbStack, WafStack]
    Properties:
      TemplateURL: !Sub "https://${ArtifactsBucket}.s3.amazonaws.com/modules/cloudfront.yaml"
      Parameters:
        ProjectName: !Ref ProjectName
        Environment: !Ref Environment
        CertificateARN: !Ref CertificateARN
        DomainName: !Ref DomainName
        WebACLArn: !GetAtt WafStack.Outputs.WebACLArn

Outputs:
  DBEndpoint:
    Value: !GetAtt RdsStack.Outputs.DBEndpoint
    Export:
      Name: !Sub "${ProjectName}-${Environment}-DBEndpoint"
  
  RedisEndpoint:
    Value: !GetAtt RedisStack.Outputs.RedisEndpoint
    Export:
      Name: !Sub "${ProjectName}-${Environment}-RedisEndpoint"

  TargetGroupArn:
    Value: !GetAtt AlbStack.Outputs.TargetGroupArn
    Export:
      Name: !Sub "${ProjectName}-${Environment}-TargetGroupArn"