AWSTemplateFormatVersion: "2010-09-09"
Description: Core Stack - ALB, RDS, Redis, EFS e CloudFront

Parameters:
  ProjectName:
    Type: String

  Environment:
    Type: String

  ArtifactsBucket:
    Type: String
    Description: S3 bucket where CloudFormation modules are stored

  CertificateARN:
    Type: String

  DomainName:
    Type: String

  WebACLArn:
    Type: String

  DBUsername:
    Type: String

  DBPassword:
    Type: String
    NoEcho: true

  DBName:
    Type: String

  DBInstanceClass:
    Type: String

Resources:

  # ==================================================
  # ALB
  # ==================================================
  AlbStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "https://${ArtifactsBucket}.s3.amazonaws.com/modules/alb.yaml"
      Parameters:
        ProjectName: !Ref ProjectName
        Environment: !Ref Environment
        CertificateARN: !Ref CertificateARN

  # ==================================================
  # RDS
  # ==================================================
  RdsStack:
    Type: AWS::CloudFormation::Stack
    DependsOn:
      - AlbStack
    Properties:
      TemplateURL: !Sub "https://${ArtifactsBucket}.s3.amazonaws.com/modules/rds.yaml"
      Parameters:
        ProjectName: !Ref ProjectName
        Environment: !Ref Environment
        DBUsername: !Ref DBUsername
        DBPassword: !Ref DBPassword
        DBName: !Ref DBName
        DBInstanceClass: !Ref DBInstanceClass

  # ==================================================
  # REDIS
  # ==================================================
  RedisStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "https://${ArtifactsBucket}.s3.amazonaws.com/modules/elasticache.yaml"
      Parameters:
        ProjectName: !Ref ProjectName
        Environment: !Ref Environment

  # ==================================================
  # EFS
  # ==================================================
  EfsStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "https://${ArtifactsBucket}.s3.amazonaws.com/modules/efs.yaml"
      Parameters:
        ProjectName: !Ref ProjectName
        Environment: !Ref Environment

  # ==================================================
  # CLOUDFRONT (entra no Core)
  # ==================================================
  CloudFrontStack:
    Type: AWS::CloudFormation::Stack
    DependsOn:
      - AlbStack
    Properties:
      TemplateURL: !Sub "https://${ArtifactsBucket}.s3.amazonaws.com/modules/cloudfront.yaml"
      Parameters:
        ProjectName: !Ref ProjectName
        Environment: !Ref Environment
        CertificateARN: !Ref CertificateARN
        DomainName: !Ref DomainName
        WebACLArn: !Ref WebACLArn

Outputs:

  AlbDnsName:
    Description: DNS do ALB
    Value: !GetAtt AlbStack.Outputs.AlbDnsName
    Export:
      Name: !Sub "${ProjectName}-${Environment}-AlbDnsName"

  TargetGroupArn:
    Description: Target Group para o ASG
    Value: !GetAtt AlbStack.Outputs.TargetGroupArn
    Export:
      Name: !Sub "${ProjectName}-${Environment}-TargetGroupArn"

  DBEndpoint:
    Description: Endpoint do banco
    Value: !GetAtt RdsStack.Outputs.DBEndpoint
    Export:
      Name: !Sub "${ProjectName}-${Environment}-DBEndpoint"

  DBPort:
    Description: Porta do banco
    Value: !GetAtt RdsStack.Outputs.DBPort
    Export:
      Name: !Sub "${ProjectName}-${Environment}-DBPort"

  RedisEndpoint:
    Description: Endpoint do Redis
    Value: !GetAtt RedisStack.Outputs.RedisEndpoint
    Export:
      Name: !Sub "${ProjectName}-${Environment}-RedisEndpoint"

  EfsId:
    Description: ID do EFS
    Value: !GetAtt EfsStack.Outputs.EfsFileSystemId
    Export:
      Name: !Sub "${ProjectName}-${Environment}-EfsId"

  CloudFrontDNS:
    Description: DNS do CloudFront
    Value: !GetAtt CloudFrontStack.Outputs.CloudFrontDNS
    Export:
      Name: !Sub "${ProjectName}-${Environment}-CloudFrontDNS"

  CloudFrontHostedZoneId:
    Description: Hosted Zone ID do CloudFront
    Value: !GetAtt CloudFrontStack.Outputs.CloudFrontHostedZoneId
    Export:
      Name: !Sub "${ProjectName}-${Environment}-CloudFrontHostedZoneId"
