AWSTemplateFormatVersion: "2010-09-09"
Description: Job 1 - Foundation Stack (VPC + Security Groups)

Parameters:
  ProjectName:
    Type: String

  Environment:
    Type: String

Resources:

  # =========================
  # VPC STACK
  # =========================
  VpcStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.amazonaws.com/SEU_BUCKET/modules/vpc.yaml
      Parameters:
        ProjectName: !Ref ProjectName
        Environment: !Ref Environment

  # =========================
  # SECURITY GROUP STACK
  # =========================
  SecurityGroupStack:
    Type: AWS::CloudFormation::Stack
    DependsOn:
      - VpcStack
    Properties:
      TemplateURL: https://s3.amazonaws.com/SEU_BUCKET/modules/sg.yaml
      Parameters:
        ProjectName: !Ref ProjectName
        Environment: !Ref Environment
