AWSTemplateFormatVersion: "2010-09-09"
Description: Job 1 - Foundation Stack (VPC + Security Groups)

Parameters:
  ProjectName:
    Type: String
  Environment:
    Type: String
    AllowedValues:
      - dev
      - prod
  ArtifactsBucket:
    Type: String

Resources:
  # 1. Stack de Rede
  VpcStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "https://${ArtifactsBucket}.s3.amazonaws.com/modules/vpc.yaml"
      Parameters:
        ProjectName: !Ref ProjectName
        Environment: !Ref Environment

  # 2. Stack de Segurança
  SecurityGroupStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: VpcStack
    Properties:
      TemplateURL: !Sub "https://${ArtifactsBucket}.s3.amazonaws.com/modules/sg.yaml"
      Parameters:
        ProjectName: !Ref ProjectName
        Environment: !Ref Environment
        VpcId: !GetAtt VpcStack.Outputs.VpcId

  # 3. Stack de Identidade (IAM Role e Instance Profile)
  IamStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "https://${ArtifactsBucket}.s3.amazonaws.com/modules/iam.yaml"
      Parameters:
        ProjectName: !Ref ProjectName
        Environment: !Ref Environment      

Outputs:
  VpcId:
    Value: !GetAtt VpcStack.Outputs.VpcId
    Export:
      Name: !Sub "${ProjectName}-vpc-${Environment}-id"

  PublicSubnetAZ1:
    Value: !GetAtt VpcStack.Outputs.PublicSubnetAZ1

  PublicSubnetAZ2:
    Value: !GetAtt VpcStack.Outputs.PublicSubnetAZ2

  PrivateAppSubnetAZ1:
    Value: !GetAtt VpcStack.Outputs.PrivateAppSubnetAZ1
    Export:
      Name: !Sub "${ProjectName}-vpc-${Environment}-private-app-az1"

  PrivateAppSubnetAZ2:
    Value: !GetAtt VpcStack.Outputs.PrivateAppSubnetAZ2
    Export:
      Name: !Sub "${ProjectName}-vpc-${Environment}-private-app-az2"

  PrivateDbSubnetAZ1:
    Value: !GetAtt VpcStack.Outputs.PrivateDbSubnetAZ1
    Export:
      Name: !Sub "${ProjectName}-vpc-${Environment}-private-db-az1"

  PrivateDbSubnetAZ2:
    Value: !GetAtt VpcStack.Outputs.PrivateDbSubnetAZ2
    Export:
      Name: !Sub "${ProjectName}-vpc-${Environment}-private-db-az2"

  AlbSecurityGroup:
    Value: !GetAtt SecurityGroupStack.Outputs.AlbSecurityGroup
    Export:
      Name: !Sub "${ProjectName}-${Environment}-AlbSG"

  AppSecurityGroup:
    Value: !GetAtt SecurityGroupStack.Outputs.AppSecurityGroup
    Export:
      Name: !Sub "${ProjectName}-${Environment}-AppSG"

  DbSecurityGroup:
    Value: !GetAtt SecurityGroupStack.Outputs.DbSecurityGroup
    Export:
      Name: !Sub "${ProjectName}-${Environment}-DbSG"

  # CORREÇÃO: Mantido seu output original com a adição do Export necessário para o ASG
  AppInstanceProfile:
    Value: !GetAtt IamStack.Outputs.AppInstanceProfileName
    Export:
      Name: !Sub "${ProjectName}-${Environment}-AppInstanceProfile"



  