AWSTemplateFormatVersion: "2010-09-09"
Description: Job 1 - Foundation Stack (VPC + Security Groups)

Parameters:
  ProjectName:
    Type: String
  Environment:
    Type: String
    AllowedValues:
      - dev
      - prod
  ArtifactsBucket:
    Type: String

Resources:
  # 1. Stack de Rede
  VpcStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "https://${ArtifactsBucket}.s3.amazonaws.com/modules/vpc.yaml"
      Parameters:
        ProjectName: !Ref ProjectName
        Environment: !Ref Environment

  # 2. Stack de Segurança
  SecurityGroupStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: VpcStack
    Properties:
      TemplateURL: !Sub "https://${ArtifactsBucket}.s3.amazonaws.com/modules/sg.yaml"
      Parameters:
        ProjectName: !Ref ProjectName
        Environment: !Ref Environment
        VpcId: !GetAtt VpcStack.Outputs.VpcId

  # 3. Stack de Identidade (IAM Role e Instance Profile)
  IamStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "https://${ArtifactsBucket}.s3.amazonaws.com/modules/iam.yaml"
      Parameters:
        ProjectName: !Ref ProjectName
        Environment: !Ref Environment      

Outputs:
  # Mantive todos os seus Outputs para visualização, mas sem o "Export" duplicado
  VpcId:
    Value: !GetAtt VpcStack.Outputs.VpcId

  PublicSubnetAZ1:
    Value: !GetAtt VpcStack.Outputs.PublicSubnetAZ1

  PublicSubnetAZ2:
    Value: !GetAtt VpcStack.Outputs.PublicSubnetAZ2

  PrivateAppSubnetAZ1:
    Value: !GetAtt VpcStack.Outputs.PrivateAppSubnetAZ1

  PrivateAppSubnetAZ2:
    Value: !GetAtt VpcStack.Outputs.PrivateAppSubnetAZ2

  PrivateDbSubnetAZ1:
    Value: !GetAtt VpcStack.Outputs.PrivateDbSubnetAZ1

  PrivateDbSubnetAZ2:
    Value: !GetAtt VpcStack.Outputs.PrivateDbSubnetAZ2

  AlbSecurityGroup:
    Value: !GetAtt SecurityGroupStack.Outputs.AlbSecurityGroup

  AppSecurityGroup:
    Value: !GetAtt SecurityGroupStack.Outputs.AppSecurityGroup

  DbSecurityGroup:
    Value: !GetAtt SecurityGroupStack.Outputs.DbSecurityGroup

  # Este valor é retornado pela stack IamStack e o Export já existe dentro do iam.yaml
  AppInstanceProfile:
    Value: !GetAtt IamStack.Outputs.AppInstanceProfileName


  