AWSTemplateFormatVersion: "2010-09-09"
Description: Master Stack - Infraestrutura Gerenciada Completa e Corrigida

Parameters:
  Environment:
    Type: String
    AllowedValues: [dev, prod]
  ProjectName:
    Type: String
  DomainName:
    Type: String
  HostedZoneId:
    Type: String
  CertificateARN:
    Type: String
  LatestAMIId:
    Type: AWS::EC2::Image::Id
  KeyName:
    Type: AWS::EC2::KeyPair::KeyName
  AppInstanceType:
    Type: String
    Default: t3.small
  DBInstanceClass:
    Type: String
    Default: db.t3.micro
  DBName:
    Type: String
    Default: stockmanager
  DBUsername:
    Type: String
  DBPassword:
    Type: String
    NoEcho: true

Resources:

  # 1. VPC
  VPCStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./modules/vpc.yaml
      Parameters:
        Environment: !Ref Environment
        ProjectName: !Ref ProjectName

  # 2. Security Groups
  SecurityStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: VPCStack
    Properties:
      TemplateURL: ./modules/security-groups.yaml
      Parameters:
        VpcId: !GetAtt VPCStack.Outputs.VpcId
        ProjectName: !Ref ProjectName
        Environment: !Ref Environment
        PublicSubnets: !Join [",", [!GetAtt VPCStack.Outputs.PublicSubnetAZ1, !GetAtt VPCStack.Outputs.PublicSubnetAZ2]]
        PrivateAppSubnets: !Join [",", [!GetAtt VPCStack.Outputs.PrivateAppSubnetAZ1, !GetAtt VPCStack.Outputs.PrivateAppSubnetAZ2]]
        PrivateDbSubnets: !Join [",", [!GetAtt VPCStack.Outputs.PrivateDbSubnetAZ1, !GetAtt VPCStack.Outputs.PrivateDbSubnetAZ2]]
        CertificateARN: !Ref CertificateARN
        LatestAMIId: !Ref LatestAMIId
        KeyName: !Ref KeyName

  # 3. ALB Web
  ALBWebStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: SecurityStack
    Properties:
      TemplateURL: ./modules/alb-web.yaml
      Parameters:
        Environment: !Ref Environment
        ProjectName: !Ref ProjectName
        VpcId: !GetAtt VPCStack.Outputs.VpcId
        # Correção do Parâmetro faltante:
        AlbSecurityGroupId: !GetAtt SecurityStack.Outputs.AlbWebSecurityGroupId
        PublicSubnets: !Join [",", [!GetAtt VPCStack.Outputs.PublicSubnetAZ1, !GetAtt VPCStack.Outputs.PublicSubnetAZ2]]
        PrivateAppSubnets: !Join [",", [!GetAtt VPCStack.Outputs.PrivateAppSubnetAZ1, !GetAtt VPCStack.Outputs.PrivateAppSubnetAZ2]]
        PrivateDbSubnets: !Join [",", [!GetAtt VPCStack.Outputs.PrivateDbSubnetAZ1, !GetAtt VPCStack.Outputs.PrivateDbSubnetAZ2]]
        CertificateARN: !Ref CertificateARN
        LatestAMIId: !Ref LatestAMIId
        KeyName: !Ref KeyName
        DBUsername: !Ref DBUsername
        DBPassword: !Ref DBPassword

  # 4. ASG App
  ASGAppStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: ALBWebStack
    Properties:
      TemplateURL: ./modules/asg-app.yaml
      Parameters:
        Environment: !Ref Environment
        ProjectName: !Ref ProjectName
        VpcId: !GetAtt VPCStack.Outputs.VpcId
        PrivateAppSubnets: !Join [",", [!GetAtt VPCStack.Outputs.PrivateAppSubnetAZ1, !GetAtt VPCStack.Outputs.PrivateAppSubnetAZ2]]
        AppTargetGroupArn: !GetAtt ALBWebStack.Outputs.WebTargetGroupArn
        AppSecurityGroupId: !GetAtt SecurityStack.Outputs.AppSecurityGroupId
        InstanceType: !Ref AppInstanceType
        LatestAMIId: !Ref LatestAMIId
        KeyName: !Ref KeyName

  # 5. RDS
  RDSStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: SecurityStack
    Properties:
      TemplateURL: ./modules/rds.yaml
      Parameters:
        Environment: !Ref Environment
        VpcId: !GetAtt VPCStack.Outputs.VpcId
        PrivateSubnetA: !GetAtt VPCStack.Outputs.PrivateDbSubnetAZ1
        PrivateSubnetB: !GetAtt VPCStack.Outputs.PrivateDbSubnetAZ2
        AppSecurityGroupId: !GetAtt SecurityStack.Outputs.AppSecurityGroupId
        DBInstanceClass: !Ref DBInstanceClass
        DBName: !Ref DBName
        DBUsername: !Ref DBUsername
        DBPassword: !Ref DBPassword

  # 6. Redis
  RedisStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: SecurityStack
    Properties:
      TemplateURL: ./modules/elasticache.yaml
      Parameters:
        Environment: !Ref Environment
        ProjectName: !Ref ProjectName
        VpcId: !GetAtt VPCStack.Outputs.VpcId
        PrivateAppSubnets: !Join [",", [!GetAtt VPCStack.Outputs.PrivateAppSubnetAZ1, !GetAtt VPCStack.Outputs.PrivateAppSubnetAZ2]]
        AppSecurityGroupId: !GetAtt SecurityStack.Outputs.AppSecurityGroupId

  # 7. EFS
  EFSStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: SecurityStack
    Properties:
      TemplateURL: ./modules/efs.yaml
      Parameters:
        Environment: !Ref Environment
        ProjectName: !Ref ProjectName
        VpcId: !GetAtt VPCStack.Outputs.VpcId
        PrivateAppSubnets: !Join [",", [!GetAtt VPCStack.Outputs.PrivateAppSubnetAZ1, !GetAtt VPCStack.Outputs.PrivateAppSubnetAZ2]]
        AppSecurityGroupId: !GetAtt SecurityStack.Outputs.AppSecurityGroupId

  # 8. Edge (CloudFront)
  EdgeStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: ALBWebStack
    Properties:
      TemplateURL: ./modules/edge.yaml
      Parameters:
        Environment: !Ref Environment
        ProjectName: !Ref ProjectName
        DomainName: !Ref DomainName
        HostedZoneId: !Ref HostedZoneId
        CertificateARN: !Ref CertificateARN
        ALBDomainName: !GetAtt ALBWebStack.Outputs.ALBWebDNS

Outputs:
  WebsiteURL:
    Description: URL pública da aplicação
    Value: !Sub "https://${DomainName}"