AWSTemplateFormatVersion: "2010-09-09"
Description: Master Stack Corrigida - Job 2 e 3 (Serviços e Computação)

Parameters:
  ProjectName:
    Type: String
  Environment:
    Type: String
  CertificateARN:
    Type: String
  DomainName:
    Type: String
  LatestAMIId:
    Type: AWS::EC2::Image::Id
  KeyName:
    Type: AWS::EC2::KeyPair::KeyName
  AppInstanceType:
    Type: String
  DBInstanceClass:
    Type: String
  DBUsername:
    Type: String
  DBPassword:
    Type: String
    NoEcho: true
  DBName:
    Type: String
    Default: "stockmanagerprod"

Resources:
  
  AlbStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: "https://s3.amazonaws.com/stock-manager-prod-artifacts/modules/alb.yaml"
      Parameters:
        ProjectName: !Ref ProjectName
        Environment: !Ref Environment
        CertificateARN: !Ref CertificateARN

  RdsStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: "https://s3.amazonaws.com/stock-manager-prod-artifacts/modules/rds.yaml"
      Parameters:
        ProjectName: !Ref ProjectName
        Environment: !Ref Environment
        DBUsername: !Ref DBUsername
        DBPassword: !Ref DBPassword
        DBName: !Ref DBName
        DBInstanceClass: !Ref DBInstanceClass

  RedisStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: "https://s3.amazonaws.com/stock-manager-prod-artifacts/modules/elasticache.yaml"
      Parameters:
        ProjectName: !Ref ProjectName
        Environment: !Ref Environment

  EfsStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: "https://s3.amazonaws.com/stock-manager-prod-artifacts/modules/efs.yaml"
      Parameters:
        ProjectName: !Ref ProjectName
        Environment: !Ref Environment

  WafStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: "https://s3.amazonaws.com/stock-manager-prod-artifacts/modules/waf-cloudfront.yaml"
      Parameters:
        ProjectName: !Ref ProjectName
        Environment: !Ref Environment

  CloudFrontStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: 
      - AlbStack
      - WafStack
    Properties:
      TemplateURL: "https://s3.amazonaws.com/stock-manager-prod-artifacts/modules/cloudfront.yaml"
      Parameters:
        ProjectName: !Ref ProjectName
        Environment: !Ref Environment
        CertificateARN: !Ref CertificateARN
        DomainName: !Ref DomainName
        WebACLArn: !GetAtt WafStack.Outputs.WebACLArn

  # ==================================================
  # JOB 3: COMPUTAÇÃO E DEPLOY (CORRIGIDO)
  # ==================================================
  AsgStack:
    Type: AWS::CloudFormation::Stack
    DependsOn:
      - AlbStack
      - RdsStack
    Properties:
      TemplateURL: "https://s3.amazonaws.com/stock-manager-prod-artifacts/modules/asg.yaml"
      Parameters:
        ProjectName: !Ref ProjectName
        Environment: !Ref Environment
        AmiId: !Ref LatestAMIId          # Mapeia LatestAMIId -> AmiId
        InstanceType: !Ref AppInstanceType # Mapeia AppInstanceType -> InstanceType
        KeyPairName: !Ref KeyName        # Mapeia KeyName -> KeyPairName
        DBUsername: !Ref DBUsername
        DBPassword: !Ref DBPassword

  # ==================================================
  # CODEDEPLOY RESOURCES
  # ==================================================
  CodeDeployServiceRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "${ProjectName}-${Environment}-codedeploy-role"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: codedeploy.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSCodeDeployRole

  CodeDeployApplication:
    Type: AWS::CodeDeploy::Application
    Properties:
      ApplicationName: !Sub "${ProjectName}-app"
      ComputePlatform: Server

  CodeDeployDeploymentGroup:
    Type: AWS::CodeDeploy::DeploymentGroup
    DependsOn:
      - AsgStack
    Properties:
      ApplicationName: !Ref CodeDeployApplication
      DeploymentGroupName: !Sub "${ProjectName}-dg-v2"
      ServiceRoleArn: !GetAtt CodeDeployServiceRole.Arn
      DeploymentStyle:
        DeploymentType: IN_PLACE
        DeploymentOption: WITHOUT_TRAFFIC_CONTROL
      AutoScalingGroups:
        - !GetAtt AsgStack.Outputs.AutoScalingGroupName

# ==================================================
# OUTPUTS PARA O JOB 3 (DNS E DEPLOY)
# ==================================================
Outputs:
  WebsiteURL:
    Description: "URL pública da aplicação"
    Value: !Sub "https://${DomainName}"

  CloudFrontDNS:
    Description: "DNS do CloudFront"
    Value: !GetAtt CloudFrontStack.Outputs.CloudFrontDNS
    Export:
      Name: !Sub "${ProjectName}-${Environment}-CF-DNS"

  CloudFrontHostedZoneId:
    Description: "Hosted Zone ID fixa do CloudFront"
    Value: "Z2FDTNDATAQYW2"
    Export:
      Name: !Sub "${ProjectName}-${Environment}-CF-ZoneID"


      

      