AWSTemplateFormatVersion: "2010-09-09"
Description: Master Stack - Infraestrutura Gerenciada (11 Módulos) - FINAL

Parameters:
  Environment:
    Type: String
    AllowedValues: [dev, prod]

  ProjectName:
    Type: String

  DomainName:
    Type: String

  HostedZoneId:
    Type: String

  CertificateARN:
    Type: String
    Description: ARN do certificado ACM (us-east-1)

  LatestAMIId:
    Type: AWS::EC2::Image::Id

  KeyName:
    Type: AWS::EC2::KeyPair::KeyName

  WebInstanceType:
    Type: String
    Default: t3.micro

  AppInstanceType:
    Type: String
    Default: t3.small

  DBInstanceClass:
    Type: String
    Default: db.t3.micro

  DBName:
    Type: String
    Default: stockmanager

  DBUsername:
    Type: String

  DBPassword:
    Type: String
    NoEcho: true

Resources:

  # 1. VPC
  VPCStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./modules/vpc.yaml
      Parameters:
        Environment: !Ref Environment
        ProjectName: !Ref ProjectName

  # 2. Security Groups
  SecurityStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: VPCStack
    Properties:
      TemplateURL: ./modules/security-groups.yaml
      Parameters:
        VpcId: !GetAtt VPCStack.Outputs.VpcId
        ProjectName: !Ref ProjectName
        Environment: !Ref Environment

  # 3. ALB Web (Internet-facing)
  ALBWebStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: SecurityStack
    Properties:
      TemplateURL: ./modules/alb-web.yaml
      Parameters:
        Environment: !Ref Environment
        ProjectName: !Ref ProjectName
        VpcId: !GetAtt VPCStack.Outputs.VpcId
        PublicSubnets: !Join
          - ","
          - - !GetAtt VPCStack.Outputs.PublicSubnetAZ1
            - !GetAtt VPCStack.Outputs.PublicSubnetAZ2
        ALBWebSecurityGroupId: !GetAtt SecurityStack.Outputs.AlbWebSecurityGroupId
        CertificateARN: !Ref CertificateARN

  # 4. ASG Web
  ASGWebStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: ALBWebStack
    Properties:
      TemplateURL: ./modules/asg-web.yaml
      Parameters:
        Environment: !Ref Environment
        ProjectName: !Ref ProjectName
        VpcId: !GetAtt VPCStack.Outputs.VpcId
        PrivateWebSubnets: !Join
          - ","
          - - !GetAtt VPCStack.Outputs.PrivateWebSubnetAZ1
            - !GetAtt VPCStack.Outputs.PrivateWebSubnetAZ2
        WebTargetGroupArn: !GetAtt ALBWebStack.Outputs.WebTargetGroupArn
        ALBWebSecurityGroupId: !GetAtt SecurityStack.Outputs.AlbWebSecurityGroupId
        InstanceType: !Ref WebInstanceType
        LatestAMIId: !Ref LatestAMIId
        KeyName: !Ref KeyName

  # 5. ALB App (Internal)
  ALBAppStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: SecurityStack
    Properties:
      TemplateURL: ./modules/alb-app.yaml
      Parameters:
        Environment: !Ref Environment
        ProjectName: !Ref ProjectName
        VpcId: !GetAtt VPCStack.Outputs.VpcId
        PrivateAppSubnets: !Join
          - ","
          - - !GetAtt VPCStack.Outputs.PrivateAppSubnetAZ1
            - !GetAtt VPCStack.Outputs.PrivateAppSubnetAZ2
        WebSecurityGroupId: !GetAtt SecurityStack.Outputs.AlbWebSecurityGroupId

  # 6. ASG App
  ASGAppStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: ALBAppStack
    Properties:
      TemplateURL: ./modules/asg-app.yaml
      Parameters:
        Environment: !Ref Environment
        ProjectName: !Ref ProjectName
        VpcId: !GetAtt VPCStack.Outputs.VpcId
        PrivateAppSubnets: !Join
          - ","
          - - !GetAtt VPCStack.Outputs.PrivateAppSubnetAZ1
            - !GetAtt VPCStack.Outputs.PrivateAppSubnetAZ2
        AppTargetGroupArn: !GetAtt ALBAppStack.Outputs.AppTargetGroupArn
        InstanceType: !Ref AppInstanceType
        LatestAMIId: !Ref LatestAMIId
        KeyName: !Ref KeyName

  # 7. RDS
  RDSStack:
    Type: AWS::CloudFormation::Stack
    DependsOn:
      - VPCStack
      - SecurityStack
    Properties:
      TemplateURL: ./modules/rds.yaml
      Parameters:
        Environment: !Ref Environment
        VpcId: !GetAtt VPCStack.Outputs.VpcId
        PrivateSubnetA: !GetAtt VPCStack.Outputs.PrivateDbSubnetAZ1
        PrivateSubnetB: !GetAtt VPCStack.Outputs.PrivateDbSubnetAZ2
        AppSecurityGroupId: !GetAtt SecurityStack.Outputs.AppSecurityGroupId
        DBInstanceClass: !Ref DBInstanceClass
        DBName: !Ref DBName
        DBUsername: !Ref DBUsername
        DBPassword: !Ref DBPassword

  # 8. Redis
  RedisStack:
    Type: AWS::CloudFormation::Stack
    DependsOn:
      - VPCStack
      - SecurityStack
    Properties:
      TemplateURL: ./modules/elasticache.yaml
      Parameters:
        Environment: !Ref Environment
        ProjectName: !Ref ProjectName
        VpcId: !GetAtt VPCStack.Outputs.VpcId
        PrivateAppSubnets: !Join
          - ","
          - - !GetAtt VPCStack.Outputs.PrivateAppSubnetAZ1
            - !GetAtt VPCStack.Outputs.PrivateAppSubnetAZ2
        AppSecurityGroupId: !GetAtt SecurityStack.Outputs.AppSecurityGroupId

  # 9. EFS
  EFSStack:
    Type: AWS::CloudFormation::Stack
    DependsOn:
      - VPCStack
      - SecurityStack
    Properties:
      TemplateURL: ./modules/efs.yaml
      Parameters:
        Environment: !Ref Environment
        ProjectName: !Ref ProjectName
        VpcId: !GetAtt VPCStack.Outputs.VpcId
        PrivateAppSubnets: !Join
          - ","
          - - !GetAtt VPCStack.Outputs.PrivateAppSubnetAZ1
            - !GetAtt VPCStack.Outputs.PrivateAppSubnetAZ2
        AppSecurityGroupId: !GetAtt SecurityStack.Outputs.AppSecurityGroupId

  # 10. Edge (CloudFront)
  EdgeStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: ALBWebStack
    Properties:
      TemplateURL: ./modules/edge.yaml
      Parameters:
        Environment: !Ref Environment
        ProjectName: !Ref ProjectName
        DomainName: !Ref DomainName
        HostedZoneId: !Ref HostedZoneId
        CertificateARN: !Ref CertificateARN
        ALBDomainName: !GetAtt ALBWebStack.Outputs.ALBWebDNS

  # 11. Route 53
  Route53Stack:
    Type: AWS::CloudFormation::Stack
    DependsOn: EdgeStack
    Properties:
      TemplateURL: ./modules/route53.yaml
      Parameters:
        ProjectName: !Ref ProjectName
        Environment: !Ref Environment
        DomainName: !Ref DomainName
        HostedZoneId: !Ref HostedZoneId
        CloudFrontDNS: !GetAtt EdgeStack.Outputs.CloudFrontDomainName

Outputs:
  WebsiteURL:
    Description: URL pública da aplicação
    Value: !Sub "https://${DomainName}"
