name: Deploy Master Infrastructure

on:
  push:
    branches: [main]

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      AWS_REGION: us-east-1
      S3_BUCKET: stock-manager-prod-artifacts
      STACK_NAME: stock-manager-master-dev
      HOSTED_ZONE_ID: Z0620408R15AZPT367P2 # ID da conta 3656
      DOMAIN_NAME: asantanadev.com

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Upload Modules to S3
        run: |
          aws s3 sync templates/modules s3://${{ env.S3_BUCKET }}/modules

      - name: Deploy ACM Module
        run: |
          aws cloudformation deploy \
            --template-file templates/modules/acm.yaml \
            --stack-name stock-manager-acm-dev \
            --parameter-overrides \
              ProjectName=stock-manager \
              Environment=dev \
              DomainName=${{ env.DOMAIN_NAME }} \
              HostedZoneId=${{ env.HOSTED_ZONE_ID }}

      - name: Wait ACM Validation
        run: |
          CERT_ARN=$(aws cloudformation describe-stacks \
            --stack-name stock-manager-acm-dev \
            --query "Stacks[0].Outputs[?OutputKey=='CertificateARN'].OutputValue" \
            --output text)
          echo "Waiting for ACM certificate validation..."
          aws acm wait certificate-validated --certificate-arn $CERT_ARN
          echo "ACM certificate validated: $CERT_ARN"

      - name: CloudFormation Package
        run: |
          aws cloudformation package \
            --template-file templates/master.yaml \
            --s3-bucket ${{ env.S3_BUCKET }} \
            --output-template-file packaged-master.yaml

      - name: Deploy Master Stack
        run: |
          # Captura o ARN dinamicamente para passar para a Master Stack
          CERT_ARN=$(aws cloudformation describe-stacks \
            --stack-name stock-manager-acm-dev \
            --query "Stacks[0].Outputs[?OutputKey=='CertificateARN'].OutputValue" \
            --output text)

          aws cloudformation deploy \
            --template-file packaged-master.yaml \
            --stack-name ${{ env.STACK_NAME }} \
            --capabilities CAPABILITY_NAMED_IAM CAPABILITY_AUTO_EXPAND \
            --parameter-overrides \
              Environment=dev \
              ProjectName=stock-manager \
              DomainName=${{ env.DOMAIN_NAME }} \
              HostedZoneId=${{ env.HOSTED_ZONE_ID }} \
              CertificateARN=$CERT_ARN \
              LatestAMIId=ami-0c101f26f147fa7fd \
              KeyName=chave-estoque-dev \
              DBUsername="${{ secrets.DB_USERNAME }}" \
              DBPassword="${{ secrets.DB_PASSWORD }}" \
              WebInstanceType=t3.micro \
              AppInstanceType=t3.small \
              DBInstanceClass=db.t3.micro
      
      - name: Notify Failure
        if: failure()
        run: |
          # Garanta que o tópico 'github-deploy-alerts' exista no console SNS
          aws sns publish \
            --topic-arn arn:aws:sns:us-east-1:365646127398:github-deploy-alerts \
            --subject "FALHA NO DEPLOY: ${{ env.STACK_NAME }}" \
            --message "O deploy falhou. Verifique os logs no GitHub Actions e o CloudFormation."