AWSTemplateFormatVersion: "2010-09-09"
Description: Master Stack - Infraestrutura completa (sem DNS e sem aplicação)

Parameters:

  ProjectName:
    Type: String

  Environment:
    Type: String

  CertificateARN:
    Type: String

  DomainName:
    Type: String

  LatestAMIId:
    Type: AWS::EC2::Image::Id

  KeyName:
    Type: AWS::EC2::KeyPair::KeyName

  AppInstanceType:
    Type: String

  DBInstanceClass:
    Type: String

  DBUsername:
    Type: String
    
  DBPassword:
    Type: String
    NoEcho: true

Resources:

  # ==================================================
  # VPC
  # ==================================================
  VPCStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: "https://s3.amazonaws.com/stock-manager-prod-artifacts/modules/vpc.yaml"
      Parameters:
        ProjectName: !Ref ProjectName
        Environment: !Ref Environment

  # ==================================================
  # SECURITY GROUPS
  # ==================================================
  SecurityGroupsStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: VPCStack
    Properties:
      TemplateURL: "https://s3.amazonaws.com/stock-manager-prod-artifacts/modules/sg.yaml"
      Parameters:
        ProjectName: !Ref ProjectName
        Environment: !Ref Environment

  # ==================================================
  # ALB
  # ==================================================
  AlbStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: SecurityGroupsStack
    Properties:
      TemplateURL: "https://s3.amazonaws.com/stock-manager-prod-artifacts/modules/alb.yaml"
      Parameters:
        ProjectName: !Ref ProjectName
        Environment: !Ref Environment
        CertificateARN: !Ref CertificateARN

  # ==================================================
  # RDS
  # ==================================================
  RdsStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: SecurityGroupsStack
    Properties:
      TemplateURL: "https://s3.amazonaws.com/stock-manager-prod-artifacts/modules/rds.yaml"
      Parameters:
        ProjectName: !Ref ProjectName
        Environment: !Ref Environment
        DBUsername: !Ref DBUsername
        DBPassword: !Ref DBPassword
        DBInstanceClass: !Ref DBInstanceClass

  # ==================================================
  # ELASTICACHE
  # ==================================================
  RedisStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: SecurityGroupsStack
    Properties:
      TemplateURL: "https://s3.amazonaws.com/stock-manager-prod-artifacts/modules/elasticache.yaml"
      Parameters:
        ProjectName: !Ref ProjectName
        Environment: !Ref Environment

  # ==================================================
  # EFS
  # ==================================================
  EfsStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: SecurityGroupsStack
    Properties:
      TemplateURL: "https://s3.amazonaws.com/stock-manager-prod-artifacts/modules/efs.yaml"
      Parameters:
        ProjectName: !Ref ProjectName
        Environment: !Ref Environment

  # ==================================================
  # ASG / COMPUTE
  # ==================================================
  AsgStack:
    Type: AWS::CloudFormation::Stack
    DependsOn:
      - AlbStack
      - RdsStack
      - RedisStack
    Properties:
      TemplateURL: "https://s3.amazonaws.com/stock-manager-prod-artifacts/modules/asg.yaml"
      Parameters:
        ProjectName: !Ref ProjectName
        Environment: !Ref Environment
        AmiId: !Ref LatestAMIId
        InstanceType: !Ref AppInstanceType
        KeyPairName: !Ref KeyName
        DBUsername: !Ref DBUsername
        DBPassword: !Ref DBPassword

  # ==================================================
  # CLOUDWATCH LOG GROUP (APP)
  # ==================================================
  CloudWatchLogsStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: AsgStack
    Properties:
      TemplateURL: "https://s3.amazonaws.com/stock-manager-prod-artifacts/modules/cloudwatch-ec2-logs.yaml"
      Parameters:
        ProjectName: !Ref ProjectName
        Environment: !Ref Environment

  # ==================================================
  # CLOUDWATCH ALARMS - ALB
  # ==================================================
  AlbAlarmsStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: AlbStack
    Properties:
      TemplateURL: "https://s3.amazonaws.com/stock-manager-prod-artifacts/modules/cloudwatch-alarms-alb.yaml"
      Parameters:
        ProjectName: !Ref ProjectName
        Environment: !Ref Environment

  # ==================================================
  # CLOUDWATCH ALARMS - ASG
  # ==================================================
  AsgAlarmsStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: AsgStack
    Properties:
      TemplateURL: "https://s3.amazonaws.com/stock-manager-prod-artifacts/modules/cloudwatch-alarms-asg.yaml"
      Parameters:
        ProjectName: !Ref ProjectName
        Environment: !Ref Environment

  # ==================================================
  # CLOUDWATCH ALB ACCESS LOGS
  # ==================================================
  AlbLogsStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: AlbStack
    Properties:
      TemplateURL: "https://s3.amazonaws.com/stock-manager-prod-artifacts/modules/cloudwatch-alb-logs.yaml"
      Parameters:
        ProjectName: !Ref ProjectName
        Environment: !Ref Environment

  # ==================================================
  # CLOUDFRONT
  # ==================================================
  CloudFrontStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: AlbStack
    Properties:
      TemplateURL: "https://s3.amazonaws.com/stock-manager-prod-artifacts/modules/cloudfront.yaml"
      Parameters:
        ProjectName: !Ref ProjectName
        Environment: !Ref Environment
        CertificateARN: !Ref CertificateARN
        DomainName: !Ref DomainName

  # ==================================================
  # WAF (CLOUDFRONT)
  # ==================================================
  WafStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: CloudFrontStack
    Properties:
      TemplateURL: "https://s3.amazonaws.com/stock-manager-prod-artifacts/modules/waf-cloudfront.yaml"
      Parameters:
        ProjectName: !Ref ProjectName
        Environment: !Ref Environment

Outputs:
  WebsiteURL:
    Description: "URL pública da aplicação"
    Value: !Sub "https://${DomainName}"

  CloudFrontDNSForRoute53:
    Description: "DNS do CloudFront para ser usado no Job 2"
    Value: !GetAtt CloudFrontStack.Outputs.CloudFrontDNS
    Export:
      Name: !Sub "${AWS::StackName}-CF-DNS"