AWSTemplateFormatVersion: "2010-09-09"
Description: Master Stack - Infraestrutura completa (sem DNS e sem aplicação)

Parameters:
  ProjectName:
    Type: String
  Environment:
    Type: String
  CertificateARN:
    Type: String
  DomainName:
    Type: String
  LatestAMIId:
    Type: AWS::EC2::Image::Id
  KeyName:
    Type: AWS::EC2::KeyPair::KeyName
  AppInstanceType:
    Type: String
  DBInstanceClass:
    Type: String
  DBUsername:
    Type: String
  DBPassword:
    Type: String
    NoEcho: true
  DBName:
    Type: String
    Default: "stockmanagerprod"
    Description: "Nome do banco de dados que será criado"

Resources:
  VPCStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: "https://s3.amazonaws.com/stock-manager-prod-artifacts/modules/vpc.yaml"
      Parameters:
        ProjectName: !Ref ProjectName
        Environment: !Ref Environment

  SecurityGroupsStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: VPCStack
    Properties:
      TemplateURL: "https://s3.amazonaws.com/stock-manager-prod-artifacts/modules/sg.yaml"
      Parameters:
        ProjectName: !Ref ProjectName
        Environment: !Ref Environment

  AlbStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: SecurityGroupsStack
    Properties:
      TemplateURL: "https://s3.amazonaws.com/stock-manager-prod-artifacts/modules/alb.yaml"
      Parameters:
        ProjectName: !Ref ProjectName
        Environment: !Ref Environment
        CertificateARN: !Ref CertificateARN

  RdsStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: SecurityGroupsStack
    Properties:
      TemplateURL: "https://s3.amazonaws.com/stock-manager-prod-artifacts/modules/rds.yaml"
      Parameters:
        ProjectName: !Ref ProjectName
        Environment: !Ref Environment
        DBUsername: !Ref DBUsername
        DBPassword: !Ref DBPassword
        DBName: !Ref DBName
        DBInstanceClass: !Ref DBInstanceClass

  RedisStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: SecurityGroupsStack
    Properties:
      TemplateURL: "https://s3.amazonaws.com/stock-manager-prod-artifacts/modules/elasticache.yaml"
      Parameters:
        ProjectName: !Ref ProjectName
        Environment: !Ref Environment

  EfsStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: SecurityGroupsStack
    Properties:
      TemplateURL: "https://s3.amazonaws.com/stock-manager-prod-artifacts/modules/efs.yaml"
      Parameters:
        ProjectName: !Ref ProjectName
        Environment: !Ref Environment

  AsgStack:
    Type: AWS::CloudFormation::Stack
    DependsOn:
      - AlbStack
      - RdsStack
      - RedisStack
    Properties:
      TemplateURL: "https://s3.amazonaws.com/stock-manager-prod-artifacts/modules/asg.yaml"
      Parameters:
        ProjectName: !Ref ProjectName
        Environment: !Ref Environment
        AmiId: !Ref LatestAMIId
        InstanceType: !Ref AppInstanceType
        KeyPairName: !Ref KeyName
        DBUsername: !Ref DBUsername
        DBPassword: !Ref DBPassword

  CloudWatchLogsStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: AsgStack
    Properties:
      TemplateURL: "https://s3.amazonaws.com/stock-manager-prod-artifacts/modules/cloudwatch-ec2-logs.yaml"
      Parameters:
        ProjectName: !Ref ProjectName
        Environment: !Ref Environment

  AlbAlarmsStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: AlbStack
    Properties:
      TemplateURL: "https://s3.amazonaws.com/stock-manager-prod-artifacts/modules/cloudwatch-alarms-alb.yaml"
      Parameters:
        ProjectName: !Ref ProjectName
        Environment: !Ref Environment

  AsgAlarmsStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: AsgStack
    Properties:
      TemplateURL: "https://s3.amazonaws.com/stock-manager-prod-artifacts/modules/cloudwatch-alarms-asg.yaml"
      Parameters:
        ProjectName: !Ref ProjectName
        Environment: !Ref Environment

  AlbLogsStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: AlbStack
    Properties:
      TemplateURL: "https://s3.amazonaws.com/stock-manager-prod-artifacts/modules/cloudwatch-alb-logs.yaml"
      Parameters:
        ProjectName: !Ref ProjectName
        Environment: !Ref Environment

  WafStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: "https://s3.amazonaws.com/stock-manager-prod-artifacts/modules/waf-cloudfront.yaml"
      Parameters:
        ProjectName: !Ref ProjectName
        Environment: !Ref Environment

  CloudFrontStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: 
      - AlbStack
      - WafStack
    Properties:
      TemplateURL: "https://s3.amazonaws.com/stock-manager-prod-artifacts/modules/cloudfront.yaml"
      Parameters:
        ProjectName: !Ref ProjectName
        Environment: !Ref Environment
        CertificateARN: !Ref CertificateARN
        DomainName: !Ref DomainName
        WebACLArn: !GetAtt WafStack.Outputs.WebACLArn

  

  CodeDeployServiceRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: stock-manager-codedeploy-role
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: codedeploy.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSCodeDeployRole

  CodeDeployApplication:
    Type: AWS::CodeDeploy::Application
    Properties:
      ApplicationName: stock-manager-app
      ComputePlatform: Server

  CodeDeployDeploymentGroup:
    Type: AWS::CodeDeploy::DeploymentGroup
    DependsOn:
      - AsgStack
      - CodeDeployServiceRole
      - CodeDeployApplication
    Properties:
      ApplicationName: stock-manager-app
      DeploymentGroupName: stock-manager-dg-v2
      ServiceRoleArn: !GetAtt CodeDeployServiceRole.Arn
      DeploymentStyle:
        DeploymentType: IN_PLACE
        DeploymentOption: WITHOUT_TRAFFIC_CONTROL
      AutoScalingGroups:
        - !GetAtt AsgStack.Outputs.AutoScalingGroupName




Outputs:
  WebsiteURL:
    Description: "URL pública da aplicação"
    Value: !Sub "https://${DomainName}"
  CloudFrontDNSForRoute53:
    Description: "DNS do CloudFront"
    Value: !GetAtt CloudFrontStack.Outputs.CloudFrontDNS
    Export:
      Name: !Sub "${AWS::StackName}-CF-DNS"

      